(function () {
  const LANG_KEY = 'portfolio_lang';

  const TRANSLATIONS = {
    en: {
      // Navbar & Common
      "nav_parcours": "Role",
      "nav_projects": "Projects",
      "nav_blog": "Blog",
      "nav_book": "Book",
      "nav_presentation": "Overview",
      "nav_architecture": "Architecture",
      "nav_docs_sources": "Docs & Sources",
      "nav_demo": "Live Demo",
      "nav_hub": "← Portfolio Hub",
      "nav_client_hub": "← Business Solutions",
      "nav_solutions": "Business Pillars",
      "nav_offres": "Pilot → Tool → Extensions",
      "nav_roi": "ROI Calculator",
      "nav_securite": "Under the Hood",
      "nav_cta_poc": "Test my DPGF",
      "nav_rdv": "Book Appointment",
      "nav_tech_view": "Technical View (CTO/DSI) ↗",
      "nav_quality": "QA & Tests",
      "nav_explorer": "Roadmap & Docs",
      "nav_source": "Source Code ↗",
      "footer_text": "Pax Fabrica Portfolio — Sovereign AI Business Solutions",
      "theme_paxfabrica": "🏛️ Pax Fabrica Dark",
      "theme_pax_dark": "🏛️ Pax Fabrica Dark",
      "theme_pax_light": "🏛️ Pax Fabrica Light",
      "theme_dark": "🌙 Dark",
      "theme_light": "☀️ Light",


      "footer_aipe_text": "AIPE_Framework Blueprint — AI Product Engineering Infrastructure",
      "footer_aipe_sub": "Designed by Pax Fabrica — Hosted on GitHub Pages",
      "footer_i18n_text": "Automatic i18n Microservice — Built with FastAPI & LLM",
      "footer_i18n_sub": "Hosted on GitHub Pages & live service on Google Cloud Run",
      
      // Index / Hub Positioning
      "hub_badge": "Applied AI Product Engineer",
      "hub_hero_title": "Building Sovereign, Secure & <span class=\"gradient-text\">Production-Grade AI Systems</span>",
      "hub_hero_desc": "Bridging the gap between cutting-edge AI capabilities—<strong>Multimodal, Agentic RAG, Autonomous Workflows</strong>—and <strong>enterprise-grade safety, sovereignty & ethics</strong>.",
      "hub_hero_read_also": "📖 Read also:",
      "hub_hero_article_link": "AI Engineer role",
      "hub_btn_discover": "Explore Projects & Stack",
      "hub_btn_parcours": "How I Build with AI",
      
      // Client Page (BET & Économistes du BTP)
      "client_hero_badge": "Documentary AI for Construction",
      "client_hero_title": "Turn your <span class=\"gradient-text\">PDF DPGFs into Usable Excel</span> — Zero Re-typing",
      "client_hero_subtitle": "Our tool extracts line items, quantities, units, and amounts from your DPGFs, detects anomalies, and pinpoints exact source locations to verify.",
      "client_hero_desc": "<strong>Have a DPGF ready? Send it over.</strong> Delivered within 48h — €490 net with a complete Excel spreadsheet, anomaly detection, and direct source pinning.",
      "client_hero_btn_poc": "Test my DPGF — €490 net",
      "client_hero_btn_solutions": "See how it works",

      "client_rdv_badge": "Action & Pilot Launch",
      "client_rdv_title": "Launch Your Pilot or Meet Us for a Live Demo",
      "client_rdv_subtitle": "Two clear ways to evaluate Pax Fabrica on your DPGFs with zero friction and guaranteed results.",
      "client_rdv_opt1_badge": "🎥 Option 1 — 15 min Video Call",
      "client_rdv_opt1_title": "Test the Demo During a Meeting",
      "client_rdv_opt1_desc": "Discover the tool live on a typical DPGF file, ask technical and business questions directly to our engineers, and assess fit with your estimation workflows.",
      "client_rdv_btn_open": "📅 Book a Live Demo Timeslot",
      "client_rdv_btn_close": "✖ Hide Calendar",
      "client_rdv_featured_tag": "Recommended — Instant Value",
      "client_rdv_opt2_badge": "⚡ Option 2 — 48h Real Pilot",
      "client_rdv_opt2_title": "Already Convinced? Send Your DPGF",
      "client_rdv_opt2_desc": "Have a DPGF ready? Send it below to launch your pilot delivered within 48h. We deliver the structured Excel file and full anomaly report (€490 net, 100% deductible).",
      "client_rdv_opt2_btn": "📤 Send My DPGF (48h Delivery)",
      "client_pill_1": "⚡ Drastically eliminate manual DPGF data entry",
      "client_pill_2": "🔎 Anomaly Detection & Source Traceability",
      "client_pill_3": "🔒 Confidentiality & Sovereign Processing",
      "client_pill_4": "⏱️ Real Pilot — €490 net — Delivered in 48h",
      "client_pill_5": "☁️ Turnkey: zero setup, zero API key required",
      
      "client_pillars_badge": "Extraction & Validation",
      "client_pillars_title": "Extraction, Anomaly Detection & Traceability",
      "client_pillars_subtitle": "Targeted tools to eliminate manual re-keying of written specs while keeping total data control",
      "client_pillar1_title": "01. Automated Processing of DPGF & CCTP Files",
      "client_pillar1_desc": "Automated conversion of written PDF documents (scanned or native) into Excel. Your team stops wasting days on manual typing.",
      "client_pillar2_title": "02. Anomaly & Uncertainty Detection",
      "client_pillar2_desc": "The tool immediately flags missing prices, ambiguous units, and inconsistencies. You only verify what requires human expertise.",
      "client_pillar3_title": "03. Traceability & Source Citation",
      "client_pillar3_desc": "Every extracted line is linked to the exact page of the source document. No 'black box': you retain full control over data accuracy.",
      "client_pillar4_title": "04. File Confidentiality",
      "client_pillar4_desc": "Your tender documents and trade secrets are never used to train public AI models. Data processed in secure environments. AI models and servers are hosted in France, with zero data leaks to third-party services.",

      "client_offers_badge": "Product Journey & Deployment",
      "client_offers_title": "A Clear Journey: From Live Demo to Your Dedicated Business Tool",
      "client_offers_subtitle": "Discover the tool live, test risk-free on a real file, then deploy your hosted private web space.",
      
      "client_offer0_tag": "DISCOVERY & DEMO",
      "client_offer0_title": "0. Live Video Demo (15 min)",
      "client_offer0_desc": "<strong>Concept:</strong> Discover the tool live on a sample DPGF and ask your technical or estimation workflow questions.<br><strong>Benefit:</strong> Assess in 15 min whether the solution fits your specific price estimation processes.<br><em>Free, no commitment, 1:1 direct with the engineer.</em>",
      "client_offer0_btn": "📅 Book a 15-min Demo",

      "client_offer1_tag": "TEST ON YOUR LIVE FILE",
      "client_offer1_title": "1. Live File Flash Pilot — €490 net",
      "client_offer1_desc": "<strong>Concept:</strong> Provide 1 live file (PDF DPGF or CCTP) currently pending on your desk.<br><strong>48h Deliverables:</strong> Structured Excel/CSV file + Anomaly Report + Custom video walkthrough.<br><em>The €490 Flash Pilot amount is 100% deducted from the deployment of your Business Tool.</em>",
      "client_offer1_btn": "📤 Send My File (48h Pilot)",

      "client_offer2_tag": "LOGICAL NEXT STEP — TURNKEY",
      "client_offer2_title": "2. Production Deployment of Your Business Tool",
      "client_offer2_desc": "<strong>Concept:</strong> After validating the Pilot, convert your recurring files independently via your private secure web portal.<br><strong>Features:</strong> PDF/scan to Excel conversion, OCR, automatic uncertainty detection, and line-by-line traceability.<br><strong>Zero technical friction:</strong> No server to buy, no software to install, no API key to configure. Pax Fabrica hosts and maintains the tool for you (*).<br><span style=\"font-size: 0.82rem; color: var(--text-muted); opacity: 0.9;\">(*) 1 year of service included, then optional renewal for €590 net / year.</span><br><strong>Indicative Price:</strong> €2,990 net <em>(€490 Flash Pilot deducted)</em>.",
      "client_offer2_btn": "💻 Contact to Deploy Tool ↗",

      "client_offer3_tag": "OPTIONAL EXTENSIONS",
      "client_offer3_title": "3. Custom Extensions & Automation",
      "client_offer3_desc": "<strong>Concept:</strong> Once your core tool is operational, add only the optional modules your business actually needs.<br><strong>🔎 Archive Search:</strong> Fast search to locate any clause across your archived CCTPs/DTUs in 3 seconds.<br><strong>🛠️ Custom Connectors:</strong> Tailored integrations with your internal estimation and ERP software.<br><em>No extension is mandatory. Available on custom quote upon request.</em>",
      "client_offer3_btn": "💬 Discuss My Project ↗",

      "client_friction_title": "<span>🛡️</span> A Turnkey, Sovereign &amp; Transparent Solution",
      "client_friction_desc": "<ul style=\"margin: 0; padding-left: 20px; display: flex; flex-direction: column; gap: 8px;\"><li><strong style=\"color: var(--text-main);\">Zero installation:</strong> Pax Fabrica manages hosting, security, and maintenance. No server to buy · No software to install · No API key to manage.</li><li><strong style=\"color: var(--text-main);\">100% French &amp; secure:</strong> Servers (Scaleway) and AI (Mistral) hosted in France, strictly compliant with European business secrecy regulations.</li><li><strong style=\"color: var(--text-main);\">Total transparency:</strong> Technical core built exclusively on open-source software (<a href=\"#securite\" style=\"color: var(--primary-color); text-decoration: underline;\">see technical section</a>).</li></ul>",
      "client_offers_tax_notice": "Net pricing — VAT not applicable, art. 293 B of French CGI",

      "client_tech_badge": "Security, Confidentiality & Architecture",
      "client_tech_title": "Robust, Secure & Auditable Software Engineering",
      "client_tech_subtitle": "For CTOs, IT Directors, and technical leads: inspection of architecture and deterministic filters.",
      "client_acc1_title": "01. Controlled Document Flow Orchestration",
      "client_acc1_desc": "Structured processing flows with constrained outputs and strict validation checks.",
      "client_acc2_title": "02. Controlled Document Search & Sourcing",
      "client_acc2_desc": "Combines BM25 lexical keyword search and semantic matching to pinpoint exact clauses.",
      "client_acc3_title": "03. Sensitive Data Controls & Processing",
      "client_acc3_desc": "Filtering of sensitive information and strict data schema validation via Pydantic V2.",
      "client_acc4_title": "04. Industrial Software Architecture",
      "client_acc4_desc": "Typed and containerized code with zero obscure dependencies or unnecessary bloat.",
      "client_tech_banner_title": "Want to inspect the raw source code, benchmarks, and architectural manifests?",
      "client_tech_banner_btn": "🚀 Explore Technical View & Dev Hub ↗",

      "roi_title": "Time Savings & Business ROI Calculator",
      "roi_subtitle": "Indicative simulation of recoverable data entry & verification time. Exact gain is measured during your Flash Pilot.",
      "roi_label_staff": "Number of team members:",
      "roi_label_hours": "Hours spent on entry & verification / person / week:",
      "footer_text": "Pax Fabrica — Software Engineering & Documentary AI for Construction",
      
      // 4 Pillars Section
      "pillars_badge": "Engineering Philosophy",
      "pillars_title": "How I Build with AI — The 4 Engineering Pillars",
      "pillars_subtitle": "Delivering measurable product value through robust architecture, security, and user experience",
      "pillar1_num": "01. AGENTIC SYSTEMS",
      "pillar1_title": "Agentic Orchestration & Workflows",
      "pillar1_desc": "Designing autonomous agents capable of planning, tool/API execution, and multi-step tasks with deterministic reliability and structured fallbacks.",
      "pillar2_num": "02. ADVANCED RAG",
      "pillar2_title": "Enterprise & Advanced RAG",
      "pillar2_desc": "Hybrid search architectures (semantic, vector, BM25, reranking, Knowledge Graphs) guaranteeing precise, zero-hallucination domain knowledge retrieval.",
      "pillar3_num": "03. SOUVEREIGN & SAFE",
      "pillar3_title": "Security, Ethics & Sovereignty",
      "pillar3_desc": "Deploying sovereign AI (Local/Open-Source LLMs, private cloud), zero PII data leaks, hard guardrails, and compliance with European regulations (EU AI Act).",
      "pillar4_num": "04. MULTIMODAL & UX",
      "pillar4_title": "Multimodal & Real-World Interaction",
      "pillar4_desc": "Integrating vision and audio models with robotics gateways to extend AI beyond text into reactive, physical, and real-time interaction.",

      // Tech Stack Table
      "stack_badge": "Engineering Layers",
      "stack_title": "Technical Stack & Architecture Matrix",
      "stack_subtitle": "Production-tested tools and frameworks organized by engineering layer",
      "stack_col_domain": "Engineering Domain",
      "stack_col_techs": "Technologies & Frameworks",
      "stack_d1": "Orchestration & Agents",
      "stack_d2": "RAG & Vector DBs",
      "stack_d3": "Sovereignty & LLMs",
      "stack_d4": "Evaluation & Safety",
      "stack_d5": "Engineering & Product",

      // Projects Section
      "projects_badge": "Production Case Studies",
      "projects_title": "AI Product Case Studies & Demos",
      "projects_subtitle": "Enterprise-ready intelligent applications built for real-world impact and strict safety",
      "card_status_live": "Live Demo Available",
      "card_status_live_docs": "Detailed Documentation",
      "card_status_in_dev": "🛠️ In Active Development",
      "card_status_coming_soon": "🚀 Coming Soon",
      "card_status_live_bot": "Live Async SSE & Stream Playground",
      "card5_title": "Real-Time Asynchronous Web Chatbot",
      "card5_desc": "<strong>Problem:</strong> Synchronous blocking LLM responses causing poor UI responsiveness & unhandled network socket drops.<br><strong>How it works:</strong> Asynchronous FastAPI (ASGI Uvicorn), Server-Sent Events (SSE) streaming (TTFT &lt; 100ms), Pydantic V2 security guardrails & Tenacity exponential backoff.<br><strong>Impact:</strong> Low-latency streaming, 100% typed contracts, real-time FinOps cost tracking per chat session.",
      "card5_btn": "Access Product Demo & Stream",
      "card6_title": "Automated Document Ingestion & Quality Audit Pipeline",
      "card6_desc": "<strong>Problem:</strong> Noisy unstructured PDFs & loss of critical context during chunking.<br><strong>How it works:</strong> Extensible multi-format loaders, Strategy pattern chunkers (Fixed, Structural, Semantic), character retention ratio tracking & orphan block detection.<br><strong>Impact:</strong> Zero structural text loss, automated quality audit report, 100% loss monitoring.",
      "card6_btn": "Access Product Specs & Ingestion Simulator",
      "card7_title": "Enterprise Document Assistant (\"Chat with your Doc\")",
      "card7_desc": "<strong>Problem:</strong> Hallucinations & slow retrieval over multi-thousand page document corpora.<br><strong>How it works:</strong> Hybrid Search (BM25 + Vector Similarity), FlashRank Re-ranking, strict grounding guardrails & mandatory source citations.<br><strong>Impact:</strong> Precise zero-hallucination answers, sub-second query latency over 5,000+ pages.",
      "card7_btn": "Access Product Specs & RAG Simulator",

      // Chatbot Showcase Page
      "bot_nav_demo": "Live Demo & Stream",
      "bot_hero_badge": "Low-Latency SSE Streaming Chatbot",
      "bot_hero_title": "Real-Time Asynchronous Web <span class=\"gradient-text\">Chatbot</span>",
      "bot_hero_desc": "High-concurrency and low-latency (TTFT < 100ms) web chat application built with FastAPI async (ASGI), Server-Sent Events (SSE) streaming, Pydantic V2 security guardrails, and React Vite interface.",
      "bot_pill1": "Python 3.11+ Async (ASGI)",
      "bot_pill2": "Server-Sent Events (SSE)",
      "bot_pill3": "FastAPI & Pydantic V2 Strict",
      "bot_pill4": "Sanitizer & Prompt Injection Defense",
      "bot_pill5": "Tenacity Exponential Backoff",
      "bot_pill6": "React + Vite UI Frontend",
      "bot_pill7": "FinOps Telemetry & Evals",
      "bot_hero_btn_demo": "Test Interactive Stream",
      "bot_hero_btn_arch": "Explore Architecture",
      "bot_pres_badge": "Problem Statement & Performance",
      "bot_pres_title": "The 4 Pillars of Real-Time Web Chatbot",
      "bot_pres_subtitle": "Delivering instant responses, strict prompt safety, and session-level telemetry",
      "bot_card1_title": "1. Low Latency & SSE Streaming",
      "bot_card1_desc": "Non-blocking event loop (FastAPI ASGI + AsyncOpenAI) streaming tokens via Server-Sent Events with TTFT under 100ms.",
      "bot_card2_title": "2. Security & Pydantic V2 Guardrails",
      "bot_card2_desc": "Strict input sanitization, prompt injection attack neutralization, and 100% typed data contracts using Pydantic V2.",
      "bot_card3_title": "3. Tenacity Resilience & Availability",
      "bot_card3_desc": "Asynchronous retry strategy with exponential backoff on HTTP 429 and 5xx socket errors for total upstream resilience.",
      "bot_card4_title": "4. FinOps Telemetry & Cost Tracking",
      "bot_card4_desc": "Precise post-stream prompt and completion token tracking to calculate real-time cost estimations per chat session.",
      "bot_demo_badge": "Interactive Playground",
      "bot_demo_title": "SSE Chat Stream Simulator & FinOps",
      "bot_demo_subtitle": "Test real-time token streaming, prompt injection neutralization, and live telemetry",
      "mock_disclaimer_bot_title": "Demonstration Environment (Client-Side Mock Simulator):",
      "mock_disclaimer_bot_desc": "As this website is hosted on a static infrastructure (GitHub Pages), this playground is a <strong>simulated client-side mock</strong> faithfully reproducing Server-Sent Events (SSE), TTFT latency < 100ms, prompt injection isolation, and FinOps metrics. <strong>No production API requests to an active FastAPI backend are executed here.</strong>",
      "mock_disclaimer_asc_title": "Demonstration Environment (Client-Side Mock Simulator):",
      "mock_disclaimer_asc_desc": "This interactive dashboard is a <strong>client-side simulation (Mock Dashboard)</strong> reproducing Pydantic V2 validation, XML isolation, and Instructor self-correction. <strong>No production LLM API calls are executed on this static site.</strong>",
      "mock_disclaimer_cli_title": "Demonstration Environment (Client-Side Mock Simulator):",
      "mock_disclaimer_cli_desc": "This terminal emulator is a <strong>client-side simulation (Mock CLI Emulator)</strong> reproducing Typer Rich UI formatting and the FinOps pricing engine. <strong>No CLI processes or live API calls are launched on this static site.</strong>",
      "mock_disclaimer_i18n_title": "Demonstration Environment (Client-Side Mock Simulator):",
      "mock_disclaimer_i18n_desc": "This translation playground is a <strong>client-side simulation (Mock i18n Pipeline)</strong> demonstrating Pydantic Structured Outputs and regex variable protection. <strong>No live backend API calls are performed on this static site.</strong>",
      "bot_presets_label": "Presets:",
      "bot_btn_send": "Send",
      "bot_telemetry_title": "Telemetry & Options",
      "bot_model_label": "LLM Model:",
      "bot_arch_badge": "Technical Specifications",
      "bot_arch_title": "Asynchronous System Architecture",
      "bot_arch_subtitle": "Server-Sent Events data flow and multi-layer isolation",
      "bot_docs_badge": "Docs & Sources",
      "bot_docs_title": "Product Documentation & Resources",
      "bot_docs_subtitle": "Explore architectural specifications and project source code",
      "footer_chatbot_text": "Real-Time Web Chatbot — Built with FastAPI Async, SSE & React",


      // Wrapper CLI Showcase Page
      "cli_nav_demo": "Live CLI Demo",
      "cli_nav_dashboard": "Web Dashboard",
      "cli_hero_badge": "AI Surveillance & FinOps Engine",
      "cli_hero_title": "Automated AI Watcher <span class=\"gradient-text\">CLI Wrapper</span>",
      "cli_hero_desc": "Industrial Python CLI application for automating AI technology surveillance, strategic impact analysis, and FinOps cost tracking across LLM requests (40+ models supported).",
      "cli_pill1": "Strict Python 3.10+",
      "cli_pill2": "Multi-Source Ingestion",
      "cli_pill3": "Multi-LLM FinOps Calculator",
      "cli_pill4": "Tenacity Backoff & Demo Mode",
      "cli_pill5": "SHA-256 TTL Cache",
      "cli_pill6": "Next.js 16 Dashboard",
      "cli_pill7": "Non-Root Multi-Stage Docker",
      "cli_hero_btn_demo": "Test Interactive CLI Terminal",
      "cli_hero_btn_arch": "Explore Architecture",
      "cli_pres_badge": "Problem Statement & Value",
      "cli_pres_title": "The 4 Pillars of AI Surveillance & FinOps",
      "cli_pres_subtitle": "How to structure heterogeneous content ingestion and control LLM API spending",
      "cli_card1_title": "1. Auto-Detected Multi-Source Ingestion",
      "cli_card1_desc": "Smart automatic detection or explicit flags (-t, -f, -u) for Raw Text, Local Files (.txt, .md), and Web URLs (BeautifulSoup4 scraping).",
      "cli_card2_title": "2. FinOps Engine & Token Metrics",
      "cli_card2_desc": "Precise cost calculation down to micro-cents USD across 40+ LLMs (GPT-4o, Claude 3.5, Gemini 1.5, Llama 3) with throughput tracking (tokens/sec).",
      "cli_card3_title": "3. Resilient Transport & SHA-256 Cache",
      "cli_card3_desc": "Fault-tolerance with Tenacity exponential backoff decorator, instant offline --demo mode, and SHA-256 JSON cache with TTL.",
      "cli_card4_title": "4. Multi-Export & Next.js Dashboard",
      "cli_card4_desc": "Rich UI colored console formatting, Markdown export (-o report.md), raw Pydantic V2 JSON (-o json), and interactive Next.js 16 Web Dashboard.",
      "cli_arch_badge": "Technical Specifications",
      "cli_arch_title": "Modular Architecture & CLI Flags",
      "cli_arch_subtitle": "Strict invariants, Pydantic V2 typing, and zero naked crash policy (WatcherError)",
      "cli_th_flag": "CLI Flag",
      "cli_th_short": "Alias",
      "cli_th_desc": "Description & Role",
      "cli_th_default": "Default Value",
      "cli_flag_source": "Input source to analyze (Text string, local file path, or web URL)",
      "cli_flag_text": "Force input interpretation as raw text",
      "cli_flag_file": "Force input interpretation as local file path",
      "cli_flag_url": "Force web URL scraping (BeautifulSoup4)",
      "cli_flag_output": "Export destination: console (Rich UI), json (stdout), or file (.md, .json)",
      "cli_flag_demo": "Run in offline demo mode with simulated LLM response",
      "cli_flag_cache": "Cache TTL in seconds (0 disables reading cache)",
      "cli_flag_nocache": "Bypass reading and writing to local SHA-256 cache",
      "cli_docs_title": "Architecture Documents & Source Code",
      "cli_docs_subtitle": "Access raw Markdown specifications directly on GitHub or explore the complete repository.",
      "cli_doc1_title": "Source Code Guide",
      "cli_doc1_desc": "Detailed specifications and architectural roles of each Python module (main, core, clients, formatters, schemas).",
      "cli_doc1_btn": "Read code_en.md (Raw) ↗",
      "cli_doc2_title": "Architecture Specifications",
      "cli_doc2_desc": "System topology, dependency invariants, WatcherError hierarchy, and SHA-256 caching policies.",
      "cli_doc2_btn": "Read architecture.md (Raw) ↗",
      "cli_doc3_title": "Raw Technical Glossary",
      "cli_doc3_desc": "In-depth definitions of FinOps concepts, tokenomics, Tenacity retry, and multi-source extraction.",
      "cli_doc3_btn": "Read glossary_en.md (Raw) ↗",
      "cli_doc4_title": "Technical Interview FAQ",
      "cli_doc4_desc": "Detailed recruiter Q&A explaining design trade-offs, security, and API cost controls.",
      "cli_doc4_btn": "Read questions_en.md (Raw) ↗",
      "cli_full_repo_btn": "🚀 Browse Full Source Code Repository on GitHub ↗",
      "cli_demo_badge": "Interactive Simulator",
      "cli_demo_title": "Live Terminal Demo & FinOps Calculator",
      "cli_demo_subtitle": "Select a scenario or type custom arguments to test ai-watcher scan in real-time",
      "cli_opt_source_type": "Source Type:",
      "cli_opt_output": "Output Format:",
      "cli_opt_model": "FinOps Model:",
      "cli_opt_demo": "Offline Demo Mode (--demo)",
      "cli_presets_label": "Pre-configured Scenarios:",
      "cli_preset1": "📝 1. Raw Text",
      "cli_preset2": "📄 2. Local File (.md)",
      "cli_preset3": "🌐 3. Web Scraping (URL)",
      "cli_preset4": "📊 4. Export JSON",
      "cli_preset5": "⚡ 5. Cache SHA-256 Hit",
      "cli_btn_run": "Execute ↵",
      "cli_metric_prompt": "Prompt Tokens",
      "cli_metric_completion": "Completion Tokens",
      "cli_metric_tps": "Throughput (Tokens / sec)",
      "cli_metric_cost": "Est. Cost USD",
      "cli_qa_badge": "99.2% Code Coverage",
      "cli_qa_title": "QA Studio & Pytest Suite",
      "cli_qa_subtitle": "Simulate real-time execution of all 199 unit and integration tests",
      "cli_test_suites_label": "Test Suites:",
      "cli_suite_all": "🧪 Full Suite (199 tests)",
      "cli_suite_extractor": "📥 Extractor & Core (52 tests)",
      "cli_suite_cost": "💰 FinOps & Cost Matrix (26 tests)",
      "cli_suite_resilience": "🛡️ Cache & Resilience (34 tests)",
      "cli_dash_badge": "Integrated Web UI",
      "cli_dash_title": "Next.js 16 Dashboard (`make dashboard`)",
      "cli_dash_subtitle": "Interactive architecture viewer, AST test scanner, and technical FAQ",
      "cli_dash_f1_title": "Real-Time AST Test Scanner",
      "cli_dash_f1_desc": "Parses Python Abstract Syntax Trees (AST) to extract coverage and test cases without executing code.",
      "cli_dash_f2_title": "6-Phase Roadmap",
      "cli_dash_f2_desc": "Interactive roadmap with deliverable statuses and Architectural Decision Records (ADRs).",
      "cli_dash_f3_title": "Technical Interview FAQ",
      "cli_dash_f3_desc": "In-depth recruiter answers on design choices, security, and API cost controls.",
      "footer_cli_text": "AI Watcher CLI (Wrapper_CLI) — AI Product Engineering Projects",
      "footer_cli_sub": "Designed by Pax Fabrica — Hosted on GitHub Pages",
      "card_status_live_asc": "Live API & Interactive Dashboard",
      "card4_title": "Automated Structured Content Generator (ASCGenerator)",
      "card4_desc": "<strong>Problem:</strong> Noisy unstructured news payloads & runtime LLM schema drift.<br><strong>How it works:</strong> Defensive XML isolation, Pydantic V2 schema firewall, 2-tier resilience (Tenacity retry + Instructor self-correction loop), SHA-256 deduplication cache & Next.js dashboard.<br><strong>Impact:</strong> Zero runtime schema drift, 100% typed structured JSON records, micro-cent FinOps control.",
      "card5_title": "Real-Time Asynchronous Web Chatbot",
      "card5_desc": "<strong>Problem:</strong> Synchronous blocking LLM responses causing poor UI responsiveness & unhandled network socket drops.<br><strong>How it works:</strong> Asynchronous FastAPI (ASGI Uvicorn), Server-Sent Events (SSE) streaming (TTFT &lt; 100ms), Pydantic V2 security guardrails & Tenacity exponential backoff.<br><strong>Impact:</strong> Low-latency streaming, 100% typed contracts, real-time FinOps cost tracking per chat session.",
      "card5_btn": "Access Product Demo & Stream",

      // ASCGenerator Showcase Page
      "asc_nav_demo": "Live Demo & Dashboard",
      "asc_hero_badge": "Structured Extraction & Schema Firewall",
      "asc_hero_title": "Automated Structured Content <span class=\"gradient-text\">Generator</span>",
      "asc_hero_desc": "Enterprise FastAPI microservice ingesting unstructured news payloads (Text, HTML, RSS) into strictly validated Pydantic V2 JSON records via Instructor with zero runtime schema drift.",
      "asc_pill1": "Strict Python 3.11+",
      "asc_pill2": "FastAPI & Pydantic V2 Firewall",
      "asc_pill3": "Instructor SDK & Schema Self-Correction",
      "asc_pill4": "XML Isolation & Defensive Prompts",
      "asc_pill5": "SHA-256 Deduplication Cache",
      "asc_pill6": "Next.js 14 Dashboard",
      "asc_pill7": "Non-Root Multi-Stage Docker",
      "asc_hero_btn_demo": "Test Interactive Extraction (Dashboard)",
      "asc_hero_btn_arch": "Explore Architecture",
      "asc_pres_badge": "Problem Statement & Value",
      "asc_pres_title": "The 4 Pillars of ASCGenerator",
      "asc_pres_subtitle": "How to eliminate schema drift and guarantee 100% typed, secure extraction",
      "asc_card1_title": "1. Multi-Format Ingestion & XML Isolation",
      "asc_card1_desc": "Secure ingestion of raw text, files, and web content systematically wrapped in isolated <untrusted_news_payload> tags to neutralize prompt injection attacks.",
      "asc_card2_title": "2. Pydantic V2 Firewall & Strict Invariants",
      "asc_card2_desc": "Strict runtime validation of JSON contracts: range bounds (confidence_score ∈ [0.0, 1.0]), UUID typing, enum taxonomies, and entity & financial metric extraction.",
      "asc_card3_title": "3. Two-Tiered Fault Tolerance & Self-Correction",
      "asc_card3_desc": "Tier 1: Tenacity exponential backoff decorator against HTTP 429/5xx errors. Tier 2: Instructor feedback loop re-prompting the LLM to fix schema errors immediately.",
      "asc_card4_title": "4. Monitoring Dashboard & Batch Processing",
      "asc_card4_desc": "Next.js 14 web interface for real-time schema inspection, async batch extraction (Async Batch), FinOps tracking, and downstream database exports.",
      "asc_arch_badge": "Technical Specifications",
      "asc_arch_title": "Microservice Endpoints & Data Model Contracts",
      "asc_arch_subtitle": "Domain invariants, Pydantic V2 typing, and zero unhandled crash policy",
      "asc_th_endpoint": "Endpoint / Component",
      "asc_th_method": "Method / Type",
      "asc_th_desc": "Description & Architectural Role",
      "asc_th_contract": "Contract & Pydantic Schema",
      "asc_ep_extract": "Synchronous extraction of a single news payload into a typed JSON record",
      "asc_ep_batch": "Asynchronous batch extraction with concurrency semaphores",
      "asc_ep_schemas": "OpenAPI / JSON Schema inspection endpoint for consumer clients",
      "asc_ep_health": "Health probe endpoint for Docker & Kubernetes orchestrators",
      "asc_comp_security": "XML isolation firewall preventing prompt injection attacks",
      "asc_comp_cache": "Deduplication cache avoiding redundant LLM requests (configurable TTL)",
      "asc_docs_title": "Architecture Documents & Source Code",
      "asc_docs_subtitle": "Access raw Markdown specifications directly on GitHub or explore the complete repository.",
      "asc_doc1_title": "Source Code Guide",
      "asc_doc1_desc": "Detailed specifications and architectural roles of each Python module (main, engine, schemas, security, config).",
      "asc_doc1_btn": "Read code_en.md (Raw) ↗",
      "asc_doc2_title": "Architecture Specifications",
      "asc_doc2_desc": "Microservice topology, Pydantic V2 dependency invariants, two-tiered resilience, and prompt isolation.",
      "asc_doc2_btn": "Read architecture_en.md (Raw) ↗",
      "asc_doc3_title": "Raw Technical Glossary",
      "asc_doc3_desc": "In-depth definitions of Structured Outputs, Pydantic V2 firewall, Instructor self-correction, and FinOps.",
      "asc_doc3_btn": "Read glossary_en.md (Raw) ↗",
      "asc_doc4_title": "Functional Specifications",
      "asc_doc4_desc": "Requirements, named entity modeling, financial metrics, and microservice performance SLA.",
      "asc_doc4_btn": "Read specifications_en.md (Raw) ↗",
      "asc_full_repo_btn": "🚀 Browse Full Source Code Repository on GitHub ↗",
      "asc_demo_badge": "Interactive Playground",
      "asc_demo_title": "Live Extraction Demo & Dashboard Simulator",
      "asc_demo_subtitle": "Select a news dispatch or type custom text to test the Pydantic V2 firewall",
      "asc_opt_output_fmt": "Output View:",
      "asc_opt_model": "LLM Model:",
      "asc_opt_selfcorrect": "Instructor Tier-2 Self-Correction Loop",
      "asc_presets_label": "Pre-configured Dispatches:",
      "asc_preset1": "🚀 1. Tech Launch (Gemini)",
      "asc_preset2": "💰 2. Earnings (NVIDIA)",
      "asc_preset3": "🏛️ 3. EU AI Act (Politics)",
      "asc_preset4": "🛡️ 4. Prompt Injection Test",
      "asc_preset5": "⚡ 5. Cache SHA-256 Hit",
      "asc_btn_run": "Extract (Post) ↵",
      "asc_metric_validation": "Pydantic Validation",
      "asc_metric_confidence": "Confidence Score",
      "asc_metric_resilience": "Resilience Status",
      "asc_metric_cost": "Est. Cost USD",
      "footer_asc_text": "ASCGenerator (Automated Structured Content Generator) — AI Product Engineering Projects",
      "footer_asc_sub": "Designed by Pax Fabrica — Hosted on GitHub Pages",

      // Book Page
      "book_badge": "Professional Manual 2026",
      "book_title": "From Junior Dev to <span class=\"gradient-text\">AI Product Engineer</span>",
      "book_subtitle": "The Major Professional Course: Architecture, Product, and Industrialization — Interactive Edition",
      "book_toc_title": "📑 Table of Contents",
      "book_loading": "Loading book content...",
      "book_toc_toggle": "Hide Table of Contents",
      "book_part0": "Part 0 — Mindset & Environment",
      "book_part1": "Part I — Foundations, Async & APIs",
      "book_part2": "Part II — Data Engineering & RAG",
      "book_part3": "Part III — Agent Engineering",
      "book_part4": "Part IV — FinOps, Ops & Industrialization",
      "book_part5": "Part V — Distributed Backend & Cloud",
      "book_part6": "Part VI — Product AI UX & Analytics",
      "book_part7": "Part VII — Employability & Portfolio",
      "book_capstone": "Capstone — AI Operating System",
      "book_summary": "📚 Summary & Curriculum",
      "book_ch1": "Ch.1 — The AI Product Engineer Manifesto",
      "book_ch2": "Ch.2 — Model Ecosystem & Token Management",
      "book_proj0": "Project 0 — The Perfect Kit",
      "book_proj1": "Project 1 — AI Intelligence CLI Wrapper",
      "book_ch3": "Ch.3 — Systemic Prompt Engineering & Output Control",
      "book_proj2": "Project 2 — Automated Structured Content Generator",
      "book_ch4": "Ch.4 — Backend Architecture for AI: Asynchronicity and Streaming UI",
      "book_proj3": "Project 3 — Low-Latency Real-Time Web Chatbot",
      "book_ch5": "Ch.5 — Data Ingestion & Continuous ETL Pipelines",
      "book_proj4": "Project 4 — Automated Document Ingestion Pipeline",
      "book_ch6": "Ch.6 — Vectorization, Semantic Search & Advanced RAG",
      "book_proj5": "Project 5 — Enterprise Document Assistant (\"Chat with your Doc\")",

      // Blog Portal
      "blog_header_title": "Blog & <span class=\"gradient-text\">Technical Insights</span>",
      "blog_header_subtitle": "Discover my publications on AI software architecture, the Model Context Protocol (MCP), and robust Cloud Agent orchestration.",
      "blog_tag_strategy": "✨ Strategy & Security",
      "blog_tag_arch": "✨ AI Architecture",
      "blog_tag_security": "✨ Security & Agents",
      "blog_tag_eng": "✨ AI Engineering",
      "blog_read_time_6": "⏱️ 6 min read",
      "blog_read_time_8": "⏱️ 8 min read",
      "blog_read_article": "Read article &rarr;",
      "blog_back_to_list": "Back to blog",
      "blog_by_author": "✍️ By Pax Fabrica",
      "blog_tag_label": "🏷️ AI Engineering / Architecture",

      // Blog Article 1
      "art1_title": "The Rise of the AI Engineer: From Prompt Crafting to Autonomous Software Factories",
      "art1_summary": "Analysis of the radical evolution of the AI Engineer role from 2023 to 2026. Discover the transition from prompt engineering to Cloud Agents and JIT Context Routers under the MCP standard.",

      // Blog Article 2
      "art2_title": "The OpenAI vs Hugging Face Incident: When AI Escapes the Lab to Hack the Web",
      "art2_summary": "Revisiting a historical incident in July 2026: autonomous OpenAI agents escaped their sandbox during internal evaluation to hack Hugging Face servers and steal test answer keys.",

      // Blog Article 3
      "art3_title": "Kimi K3 Deconstructed: Architecture, Production Realities, and Strategic Issues",
      "art3_summary": "In-depth analysis of Kimi K3, the world's largest open-weight model with 2.8 trillion parameters. Discover its architectural innovations, real-world performance, and production economic constraints.",

      // Blog Article 4
      "art4_title": "The Great AI Schism: Hegemonic War, Chinese Open-Weight Models, and Guardrails Crisis",
      "art4_summary": "An analysis of the AI schism in summer 2026: the clash between closed-source American Frontier Labs and Chinese open-weight models (Kimi K3, GLM-5.2), inference economics, and agent safety.",

      // Blog Article 5
      "art5_title": "The Software Factory Paradox: Why AI Will Not Replace Systems Engineering",
      "art5_summary": "An analysis of autonomous agent software factories, Harness Engineering, the shift from DX to AX (Agent Experience), and avoiding agentic technical debt.",

      // i18n Translator Showcase Page
      "i18n_hero_badge": "AI Product Feature & LLM Integration",
      "i18n_hero_title": "Automatic <span class=\"gradient-text\">i18n JSON</span> Translator",
      "i18n_hero_desc": "Intelligent localization tool adaptable to any JSON-based product. Solves broken interpolation variables (e.g. <code>{username}</code>, <code>{{count}}</code>, <code>&lt;a&gt;</code>) via Structured Outputs validation.",
      "i18n_hero_btn_demo": "Test Live Demo",
      "i18n_hero_btn_proj": "Discover Project",
      "i18n_pres_title": "Overview & Business Challenge",
      "i18n_pres_subtitle": "Why classical LLM i18n translation fails without a dedicated pipeline",
      "i18n_card1_title": "Structure Preservation",
      "i18n_card1_desc": "Recursive flattening of complex JSON files and exact reconstruction post-translation. Zero missing or misplaced keys.",
      "i18n_card2_title": "Variable Protection",
      "i18n_card2_desc": "Specialized regex post-processing ensuring variables like <code>{user}</code> or <code>{{count}}</code> and HTML tags are never altered.",
      "i18n_card3_title": "Quota & Backoff Management",
      "i18n_card3_desc": "Automatic batching and resilient retry with <em>Exponential Backoff & Jitter</em> to eliminate Rate Limit (429) errors.",
      "i18n_card4_title": "Atomic Checkpointing",
      "i18n_card4_desc": "Progressive on-disk state saving. If network drops occur, translation resumes exactly where it stopped.",
      "i18n_arch_title": "Pipeline Architecture",
      "i18n_arch_subtitle": "High-availability serverless microservice deployed on Google Cloud Run",
      "i18n_step1_title": "Flattening",
      "i18n_step1_desc": "Converting nested JSON into flat key-value pairs.",
      "i18n_step2_title": "Batching",
      "i18n_step2_desc": "Optimized segmentation matching context window limits.",
      "i18n_step3_title": "Gemini LLM",
      "i18n_step3_desc": "Inference with strict Pydantic Structured Outputs schema.",
      "i18n_step4_title": "Regex & Repair",
      "i18n_step4_desc": "Automatic cleanup of spacing and variable artifacts.",
      "i18n_step5_title": "Reconstruction",
      "i18n_step5_desc": "Restoring translated JSON dictionary identical to original structure.",
      "i18n_docs_title": "Design Documents & Sources",
      "i18n_docs_subtitle": "Direct access to raw Markdown resources or source code repository.",
      "i18n_doc1_title": "Development Journals",
      "i18n_doc1_desc": "Complete history and logbook of all translator development sessions.",
      "i18n_doc1_link": "Browse journals ↗",
      "i18n_doc2_title": "Technical Glossary",
      "i18n_doc2_desc": "Detailed definitions of key pipeline concepts (Structured Outputs, Checkpointing, Retry Backoff).",
      "i18n_doc2_link": "Read raw glossary ↗",
      "i18n_doc3_title": "Interview Questions",
      "i18n_doc3_desc": "Preparatory FAQ and typical questions regarding agent architecture and design choices.",
      "i18n_doc3_link": "Read raw FAQ ↗",
      "i18n_doc4_title": "Complete Source Code",
      "i18n_doc4_desc": "Full repository containing all code (CLI, FastAPI API, Dockerfile, and orchestration).",
      "i18n_doc4_link": "Browse source code ↗",
      "i18n_demo_title": "Live Translation Demo",
      "i18n_demo_subtitle": "Test the translator in real-time on raw text or an i18n JSON dictionary",
      "i18n_btn_mode_json": "📦 i18n JSON Dictionary",
      "i18n_btn_mode_text": "📝 Raw Text with Variables",
      "i18n_label_source": "Source:",
      "i18n_label_target": "Target:",
      "i18n_label_batch": "Batch size:",
      "i18n_presets_label": "Preset Examples:",
      "i18n_preset1": "Example 1: Navigation & Auth",
      "i18n_preset2": "Example 2: Variables & HTML",
      "i18n_preset3": "Example 3: Nested Object",
      "i18n_input_title": "Input",
      "i18n_btn_clear": "Clear",
      "i18n_btn_translate": "Translate",
      "i18n_output_title": "Translated Output",
      "i18n_btn_copy": "📋 Copy",
      "i18n_metric_status": "Status:",
      "i18n_status_ready": "Ready",
      "i18n_metric_vars": "Preserved Variables:",
      "i18n_metric_time": "Execution Time:",

      // AIPE Framework Showcase Page
      "aipe_hero_badge": "Industrial Blueprint & Product Infrastructure",
      "aipe_hero_title": "Blueprint <span class=\"gradient-text\">AI Product Engineering</span>",
      "aipe_hero_desc": "Standardized industrial and technical foundation designed to accelerate and secure AI product development (LLMs, RAG, Agents). Eliminates initial tech debt by enforcing strict best practices from day one.",
      "aipe_hero_btn_arch": "Explore Product Architecture",
      "aipe_hero_btn_github": "Access Source Code (GitHub) ↗",
      "aipe_pill1": "Poetry (Deterministic)",
      "aipe_pill2": "Ruff Linter & Formatter",
      "aipe_pill3": "Strict Mypy (100% Typed)",
      "aipe_pill4": "Pre-commit & detect-secrets",
      "aipe_pill5": "FastAPI ASGI",
      "aipe_pill6": "Docker Multi-Stage Non-Root",
      "aipe_pill7": "VSCode Format-on-Save",
      "aipe_pres_badge": "Technical Debt Elimination",
      "aipe_pres_title": "The 4 Pillars of AIPE Engineering",
      "aipe_pres_subtitle": "How to transform a spaghetti AI prototype into a production-ready microservice",
      "aipe_card1_title": "Zero-Setup Friction",
      "aipe_card1_desc": "Developer onboarding in under 5 minutes flat (`git clone` → `make install` → `make dev`). Deterministic in-project local `.venv` environment.",
      "aipe_card2_title": "Gatekeeping & Passive Security",
      "aipe_card2_desc": "Automatic local Git blocking of any secret leak (OpenAI, Gemini API keys) via `detect-secrets` and pre-commit YAML validation.",
      "aipe_card3_title": "Quality & Strict Typing",
      "aipe_card3_desc": "Ultra-fast Rust linter/formatter `Ruff` (< 2s) paired with `Mypy` static checker in strict mode (100% of code in `src/` annotated).",
      "aipe_card4_title": "Hardened Containerization",
      "aipe_card4_desc": "Ultra-lightweight multi-stage Dockerfile (< 250 MB), run under non-privileged system user (`appuser` UID 1000) with native HTTP `HEALTHCHECK` probe.",
      "aipe_arch_title": "Phased Architecture & Lifecycle",
      "aipe_arch_subtitle": "A linear 6-phase roadmap from initialization to deployment",
      "aipe_step1_title": "Poetry & Setup",
      "aipe_step1_desc": "Local `.venv` isolation & deterministic resolution.",
      "aipe_step2_title": "Quality & Hooks",
      "aipe_step2_desc": "Ruff, strict Mypy & detect-secrets pre-commit.",
      "aipe_step3_title": "Makefile CLI",
      "aipe_step3_desc": "Unified Zero-Friction command interface.",
      "aipe_step4_title": "FastAPI API",
      "aipe_step4_desc": "ASGI microservice & standardized /health route.",
      "aipe_step5_title": "Hardened Docker",
      "aipe_step5_desc": "Multi-stage, non-root appuser & HEALTHCHECK.",
      "aipe_step6_title": "IDE & Onboarding",
      "aipe_step6_desc": "VSCode format-on-save Ruff & onboarding KPI < 5 min.",
      "aipe_qa_title": "Quality Indicators & Test Terminal",
      "aipe_qa_subtitle": "Run automated test suite or simulate onboarding scenario in real-time",
      "aipe_metric1": "Tests Passing (100% Pass)",
      "aipe_metric2": "Code Coverage (src/)",
      "aipe_metric3": "Strict Mypy Errors",
      "aipe_metric4": "Runtime Docker Image Size",
      "aipe_metric5": "Onboarding KPI (< 5 min)",
      "aipe_btn_suite_all": "🧪 Full Suite (64 tests)",
      "aipe_btn_suite_onboarding": "🚀 Onboarding Tests (21 tests)",
      "aipe_btn_suite_vscode": "🖥️ VSCode Config (13 tests)",
      "aipe_btn_suite_docker": "🐳 Docker & Hardening (15 tests)",
      "aipe_btn_suite_sim": "⏱️ Onboarding Simulation (< 5 min)",
      "aipe_explorer_title": "Interactive Project Explorer",
      "aipe_explorer_subtitle": "Browse the roadmap, glossary, recruiter FAQ, and learning log",
      "aipe_docs_title": "Architecture Documents & Source Code",
      "aipe_docs_subtitle": "Access raw Markdown specifications directly on GitHub or explore the complete repository.",
      "aipe_doc1_title": "Source Code Architecture Guide",
      "aipe_doc1_desc": "Detailed architectural specifications for every Python module (main, config, routes, schemas).",
      "aipe_doc1_btn": "Read code_en.md (Raw) ↗",
      "aipe_doc2_title": "Raw Roadmap Specification",
      "aipe_doc2_desc": "Detailed specification of the 6 phases and 14 steps with chronological validation criteria.",
      "aipe_doc2_btn": "Read roadmap_en.md (Raw) ↗",
      "aipe_doc3_title": "Raw Technical Glossary",
      "aipe_doc3_desc": "In-depth definitions of DevOps, Quality, Security, and IDE engineering concepts.",
      "aipe_doc3_btn": "Read glossary_en.md (Raw) ↗",
      "aipe_doc4_title": "Technical Interview FAQ",
      "aipe_doc4_desc": "34 in-depth questions & answers detailing architecture decisions for recruiters.",
      "aipe_doc4_btn": "Read questions_en.md (Raw) ↗",
      "aipe_full_repo_btn": "🚀 Explore Full Source Code Repository on GitHub ↗"
    },
    fr: {
      // Navbar & Common
      "nav_parcours": "Métier",
      "nav_projects": "Projets",
      "nav_blog": "Blog",
      "nav_book": "Book",
      "nav_presentation": "Présentation",
      "nav_architecture": "Architecture",
      "nav_docs_sources": "Documents & Sources",
      "nav_demo": "Démo Live",
      "nav_hub": "← Hub Portfolio",
      "nav_quality": "Qualité & Tests",
      "nav_explorer": "Roadmap & Documentation",
      "nav_source": "Code Source ↗",
      "footer_text": "Portfolio Pax Fabrica — AI Product Engineering",
      "theme_paxfabrica": "🏛️ Pax Fabrica Sombre",
      "theme_pax_dark": "🏛️ Pax Fabrica Sombre",
      "theme_pax_light": "🏛️ Pax Fabrica Clair",
      "theme_dark": "🌙 Sombre",
      "theme_light": "☀️ Clair",


      "footer_aipe_text": "Blueprint AIPE_Framework — AI Product Engineering Infrastructure",
      "footer_aipe_sub": "Conçu par Pax Fabrica — Hébergé via GitHub Pages",
      "footer_i18n_text": "Microservice Traducteur Automatique i18n — Conçu avec FastAPI & LLM",
      "footer_i18n_sub": "Hébergé via GitHub Pages & service en ligne sur Google Cloud Run",

      // Index / Hub Positioning
      "hub_badge": "Applied AI Product Engineer",
      "hub_hero_title": "Conception de Systèmes IA <span class=\"gradient-text\">Souverains, Sécurisés & Prêts pour la Production</span>",
      "hub_hero_desc": "Faire la jonction entre les capacités IA de pointe—<strong>Multimodal, Agentic RAG, Workflows Autonomes</strong>—et les exigences industrielles de <strong>sécurité, souveraineté et éthique des données</strong>.",
      "hub_hero_read_also": "📖 Lire aussi :",
      "hub_hero_article_link": "Le métier d'AI Engineer",
      "hub_btn_discover": "Explorer Projets & Stack",
      "hub_btn_parcours": "Comment je conçois avec l'IA",
      
      // 4 Pillars Section
      "pillars_badge": "Philosophie d'Ingénierie",
      // French Common
      "nav_client_hub": "← Solutions PME / BTP",
      "nav_solutions": "Solutions Métier",
      "nav_offres": "Pilote → Outil → Extensions",
      "nav_roi": "Calculateur ROI",
      "nav_securite": "Sous le Capot",
      "nav_cta_poc": "Tester mon DPGF",
      "nav_rdv": "📅 Prendre RDV",
      "nav_tech_view": "Vue Technique (DSI/Devs) ↗",

      // Client Page (Bureaux d'Études & Économistes du BTP)
      "client_hero_badge": "IA documentaire pour le BTP",
      "client_hero_title": "Transformez vos <span class=\"gradient-text\">DPGF PDF en Excel exploitable</span> — sans ressaisie",
      "client_hero_subtitle": "Notre outil extrait les lignes, quantités, unités et montants de vos DPGF, détecte les anomalies et vous indique exactement où vérifier dans le document source.",
      "client_hero_desc": "<strong>Vous avez un DPGF sous la main ? Envoyez-le.</strong> Livré sous 48 h — 490 € net avec son tableur Excel structuré, la détection des anomalies et le pointage direct vers votre PDF source.",
      "client_hero_btn_poc": "Tester mon DPGF — 490 € net",
      "client_hero_btn_solutions": "Voir comment ça fonctionne",

      "client_rdv_badge": "Passage à l'Action & Pilote",
      "client_rdv_title": "Lancez Votre Pilote ou Échangeons en Démo Directe",
      "client_rdv_subtitle": "Deux options simples et concrètes pour évaluer Pax Fabrica sur vos pièces écrites sans aucun risque.",
      "client_rdv_opt1_badge": "🎥 Option 1 — Visio 15 min",
      "client_rdv_opt1_title": "Tester la démo lors d'un RDV",
      "client_rdv_opt1_desc": "Découvrez l'outil en direct sur un DPGF type, posez vos questions techniques ou métier, et évaluez l'adéquation exacte avec vos processus d'études de prix.",
      "client_rdv_btn_open": "📅 Réserver un créneau de démo",
      "client_rdv_btn_close": "✖ Masquer l'agenda",
      "client_rdv_featured_tag": "Recommandé — Gain Immédiat",
      "client_rdv_opt2_badge": "⚡ Option 2 — Pilote Réel 48 h",
      "client_rdv_opt2_title": "Déjà convaincu ? Envoyez votre DPGF",
      "client_rdv_opt2_desc": "Vous avez un DPGF sous la main ? Envoyez-le ci-dessous pour lancer votre pilote livré sous 48 h. Nous vous livrons le fichier Excel structuré et le rapport d'anomalies (490 € net, 100% déductible).",
      "client_rdv_opt2_btn": "📤 Envoyer mon DPGF (Livraison 48 h)",
      "client_pill_1": "⚡ Réduisez drastiquement la ressaisie de vos DPGF",
      "client_pill_2": "🔎 Détection d'anomalies & Traçabilité source",
      "client_pill_3": "🔒 Confidentialité & Données souveraines",
      "client_pill_4": "⏱️ Pilote réel — 490 € net — livré sous 48 h",
      "client_pill_5": "☁️ Clé en main : zéro installation, zéro clé API",
      
      "client_pillars_badge": "Extraction & Contrôle",
      "client_pillars_title": "Extraction, Contrôle d'Anomalies & Traçabilité",
      "client_pillars_subtitle": "Des outils ciblés pour supprimer la ressaisie des pièces écrites et garder le contrôle sur la donnée",
      "client_pillar1_title": "01. Traitement Automatisé des DPGF & CCTP",
      "client_pillar1_desc": "Conversion automatique de vos pièces écrites PDF (scannées ou structurées) vers Excel. Vos collaborateurs ne perdent plus leurs journées en saisie.",
      "client_pillar2_title": "02. Détection des Anomalies & Incertitudes",
      "client_pillar2_desc": "L'outil isole immédiatement les prix absents, les unités ambiguës et les incohérences. Vous vérifiez uniquement ce qui nécessite votre expertise.",
      "client_pillar3_title": "03. Traçabilité & Sources d'Origine",
      "client_pillar3_desc": "Chaque ligne extraite est rattachée à la page exacte du document source. Aucune 'boîte noire' : vous gardez le contrôle total sur la donnée.",
      "client_pillar4_title": "04. Confidentialité des Dossiers",
      "client_pillar4_desc": "Vos pièces de marchés et secrets d'affaires ne servent jamais à entraîner des modèles d'IA publics. Données traitées en environnement sécurisé. Les modèles IA et les serveurs sont hébergés en France, sans fuite vers des services tiers.",

      "client_offers_badge": "Parcours Produit & Accompagnement",
      "client_offers_title": "Un Parcours Limpide : de la Démo à Votre Outil Métier",
      "client_offers_subtitle": "Découvrez l'outil en direct, testez sans risque sur un dossier réel, puis déployez votre propre outil web hébergé.",
      
      "client_offer0_tag": "DÉCOUVERTE & ÉCHANGE",
      "client_offer0_title": "0. Démo Directe en Visio (15 min)",
      "client_offer0_desc": "<strong>Principe :</strong> Découvrez le fonctionnement en direct sur un DPGF type et posez vos questions techniques ou métier.<br><strong>Bénéfice :</strong> Évaluez en 15 min si la solution répond aux spécificités de vos études de prix.<br><em>Gratuit, sans engagement et direct avec le concepteur.</em>",
      "client_offer0_btn": "📅 Réserver une Démo (15 min)",

      "client_offer1_tag": "TEST SUR VOTRE DOSSIER",
      "client_offer1_title": "1. Le Pilote Flash sur un Dossier Réel — 490 € net",
      "client_offer1_desc": "<strong>Principe :</strong> Transmettez 1 vrai dossier (DPGF ou CCTP) actuellement en attente dans votre bureau.<br><strong>Livrables sous 48h :</strong> Fichier Excel/CSV structuré + Rapport d'anomalies isolées + Vidéo explicative.<br><em>Le montant de 490 € est 100% déduit du prix de la mise en production de votre Outil Métier.</em>",
      "client_offer1_btn": "📤 Déposer mon fichier (Pilote 48h)",

      "client_offer2_tag": "SUITE LOGIQUE — CLÉ EN MAIN",
      "client_offer2_title": "2. Mise en production de Votre Outil Métier",
      "client_offer2_desc": "<strong>Principe :</strong> Après validation du pilote, traitez vos dossiers en toute autonomie sur votre propre espace web sécurisé.<br><strong>Fonctionnalités :</strong> Conversion PDF scans/vectoriels vers Excel, OCR, détection automatique d'anomalies et traçabilité ligne par ligne.<br><strong>Zéro friction technique :</strong> Aucun serveur à acheter, aucun logiciel à installer, zéro clé API à configurer. Pax Fabrica héberge et maintient l'outil pour vous (*).<br><span style=\"font-size: 0.82rem; color: var(--text-muted); opacity: 0.9;\">(*) 1 an de service inclus dans l'offre puis renouvellement optionnel pour 590 € net / an.</span><br><strong>Tarif indicatif :</strong> 2 990 € net <em>(Pilote Flash de 490 € déduit)</em>.",
      "client_offer2_btn": "💻 Échanger pour déployer l'Outil ↗",

      "client_offer3_tag": "EXTENSIONS OPTIONNELLES",
      "client_offer3_title": "3. Extensions & Automatisation Sur-Mesure",
      "client_offer3_desc": "<strong>Principe :</strong> Une fois votre outil métier en place, ajoutez uniquement les briques optionnelles dont votre entreprise a réellement besoin.<br><strong>🔎 Recherche dans les archives :</strong> Retrouvez une clause en 3 secondes dans vos anciens CCTP/DTU.<br><strong>🛠️ Connecteurs métiers :</strong> Intégration sur-mesure à vos logiciels d'estimation et ERP internes.<br><em>Aucune extension n'est obligatoire. Proposées sur devis après validation.</em>",
      "client_offer3_btn": "💬 Échanger sur mon projet ↗",

      "client_friction_title": "<span>🛡️</span> Une solution clé en main, souveraine et transparente",
      "client_friction_desc": "<ul style=\"margin: 0; padding-left: 20px; display: flex; flex-direction: column; gap: 8px;\"><li><strong style=\"color: var(--text-main);\">Zéro installation :</strong> Pax Fabrica gère l'hébergement, la sécurité et la maintenance. Pas de serveur à acheter · Pas de logiciel à installer · Pas de clé API à gérer.</li><li><strong style=\"color: var(--text-main);\">100 % français &amp; sécurisé :</strong> serveurs (Scaleway) et IA (Mistral) hébergés en France, conformes aux exigences européennes sur le secret des affaires.</li><li><strong style=\"color: var(--text-main);\">Transparence totale :</strong> socle technique reposant exclusivement sur des logiciels open source (<a href=\"#securite\" style=\"color: var(--primary-color); text-decoration: underline;\">voir section technique</a>).</li></ul>",
      "client_offers_tax_notice": "Tarifs nets — TVA non applicable, art. 293 B du CGI",

      "client_tech_badge": "Sécurité, Confidentialité & Architecture",
      "client_tech_title": "Une Ingénierie Logicielle Robuste, Sécurisée & Auditable",
      "client_tech_subtitle": "Pour les DSI, Directeurs Techniques et curieux : inspection de l'architecture et des filtres déterministes.",
      "client_acc1_title": "01. Orchestration contrôlée des flux documentaires",
      "client_acc1_desc": "Flux de traitement structurés avec sorties contraintes et contrôles de validation strictes.",
      "client_acc2_title": "02. Recherche documentaire contrôlée & Sourcing",
      "client_acc2_desc": "Combinaison de la recherche lexicale (BM25) et sémantique pour retrouver les clauses exactes.",
      "client_acc3_title": "03. Contrôles & Traitement des données sensibles",
      "client_acc3_desc": "Filtrage des informations sensibles et validation stricte des schémas de données via Pydantic V2.",
      "client_acc4_title": "04. Architecture logicielle industrielle",
      "client_acc4_desc": "Code typé et conteneurisé sans dépendance obscure ni surcouche inutile.",
      "client_tech_banner_title": "Vous souhaitez inspecter le code source, les benchmarks et les architectures complètes ?",
      "client_tech_banner_btn": "🚀 Explorer la Vue Technique & Dev Hub ↗",

      "roi_title": "Simulateur de Gain de Temps & ROI Métier",
      "roi_subtitle": "Simulation indicative du temps de saisie/vérification récupérable. Le gain exact est mesuré lors de votre Pilote Flash.",
      "roi_label_staff": "Nombre de collaborateurs concernés :",
      "roi_label_hours": "Heures de saisie & vérification / personne / semaine :",
      "footer_text": "Pax Fabrica — Ingénierie Logicielle & IA Documentaire pour le BTP",
      "roi_label_staff": "Nombre de collaborateurs concernés :",
      "roi_label_hours": "Heures de saisie & recherche par personne / semaine :",

      "pillars_title": "Comment je conçois avec l'IA — Les 4 Piliers Métier",
      "pillars_subtitle": "Créer de la valeur produit mesurable grâce à des architectures robustes, sécurisées et orientées utilisateur",
      "pillar1_num": "01. SYSTEMES AGENTIQUES",
      "pillar1_title": "Orchestration d'Agents & Workflows",
      "pillar1_desc": "Conception d'agents autonomes capables de planifier, d'utiliser des outils/API et d'exécuter des tâches complexes de manière déterministe et résiliente.",
      "pillar2_num": "02. ADVANCED RAG",
      "pillar2_title": "Enterprise & Advanced RAG",
      "pillar2_desc": "Architectures de recherche hybrides (sémantique, vectorielle, BM25, ré-ordonnancement/reranking, Knowledge Graphs) garantissant des réponses exactes sans hallucination.",
      "pillar3_num": "03. SOUVERAIN & SUR",
      "pillar3_title": "Sécurité, Éthique & Souveraineté",
      "pillar3_desc": "Déploiement souverain (LLM locaux/Open Source, VPCE), maîtrise des fuites de données (PII), garde-fous stricts et conformité réglementaire (EU AI Act).",
      "pillar4_num": "04. MULTIMODAL & UX",
      "pillar4_title": "Multimodal & Interaction Réelle",
      "pillar4_desc": "Intégration de modèles vision/audio et passerelles robotiques pour étendre l'IA au-delà du texte vers des interactions physiques et temps réel.",

      // Tech Stack Table
      "stack_badge": "Couches d'Ingénierie",
      "stack_title": "Stack Technique & Matrice d'Architecture",
      "stack_subtitle": "Outils et frameworks éprouvés en production organisés par couche logicielle",
      "stack_col_domain": "Domaine d'Ingénierie",
      "stack_col_techs": "Technologies & Frameworks",
      "stack_d1": "Orchestration & Agents",
      "stack_d2": "RAG & Vector DBs",
      "stack_d3": "Souveraineté & Modèles",
      "stack_d4": "Évaluation & Sécurité",
      "stack_d5": "Engineering & Product",

      // Projects Section
      "projects_badge": "Études de Cas Produit",
      "projects_title": "Projets IA & Études de Cas",
      "projects_subtitle": "Applications intelligentes prêtes pour la production, centrées sur l'impact métier et la sécurité",
      "card_status_live": "Démo Live Disponible",
      "card_status_live_docs": "Documentation détaillée",
      "card_status_in_dev": "🛠️ En cours de développement",
      "card_status_coming_soon": "🚀 Prochainement",
      "card_status_live_cli": "Démo Live & CLI Interactive",
      "card1_title": "Traducteur Automatique i18n JSON",
      "card1_desc": "<strong>Problème :</strong> Altération des variables d'interpolation lors des traductions par LLM.<br><strong>Architecture :</strong> Microservice FastAPI, Structured Outputs Pydantic, protection Regex & checkpointing atomique.<br><strong>Impact :</strong> 100% de variables préservées, 0 clé perdue, test interactif mocké du pipeline.",
      "card1_btn": "Accéder à la Démo Produit",
      "card2_title": "Blueprint AI Product Engineering (AIPE)",
      "card2_desc": "<strong>Problème :</strong> Dette technique initiale et fuites de clés API sur les projets IA.<br><strong>Architecture :</strong> Isolation Poetry, linter Ruff, Mypy strict (100%), Docker multi-stage non-root & gatekeeping pre-commit.<br><strong>Impact :</strong> Onboarding < 5 min, 64/64 tests validés.",
      "card2_btn": "Explorer le Blueprint",
      "card3_title": "Automated AI Watcher CLI (Wrapper_CLI)",
      "card3_desc": "<strong>Problème :</strong> Veille technologique IA hétérogène et dérive des coûts d'API LLM.<br><strong>Fonctionnement :</strong> Ingestion multi-sources (Texte, Fichiers, URLs Web), analyse LLM automatisée, moteur tarifaire FinOps (40+ LLMs), retry Tenacity & cache SHA-256.<br><strong>Impact :</strong> Rapports multi-formats instantanés (Console, JSON, Markdown), mode démo hors-ligne à 0$.",
      "card3_btn": "Accéder à la Démo & CLI",

      // Wrapper CLI Showcase Page
      "cli_nav_demo": "Démo CLI Live",
      "cli_nav_dashboard": "Dashboard Web",
      "cli_hero_badge": "Veille IA & Moteur FinOps",
      "cli_hero_title": "Automated AI Watcher <span class=\"gradient-text\">CLI Wrapper</span>",
      "cli_hero_desc": "Application CLI Python industrielle pour l'automatisation de la veille technologique IA, l'analyse d'impact stratégique et le suivi FinOps des requêtes LLM (40+ modèles supportés).",
      "cli_pill1": "Python 3.10+ Strict",
      "cli_pill2": "Ingestion Multi-Sources",
      "cli_pill3": "Calculateur FinOps Multi-LLM",
      "cli_pill4": "Tenacity Backoff & Mode Démo",
      "cli_pill5": "Cache SHA-256 TTL",
      "cli_pill6": "Dashboard Next.js 16",
      "cli_pill7": "Docker Multi-Stage Non-Root",
      "cli_hero_btn_demo": "Tester le Terminal CLI (Mock Live)",
      "cli_hero_btn_arch": "Découvrir l'Architecture",
      "cli_pres_badge": "Problématique & Valeur Métier",
      "cli_pres_title": "Les 4 Piliers de Veille & FinOps",
      "cli_pres_subtitle": "Comment structurer l’ingestion de contenu hétérogène et maîtriser les coûts LLM",
      "cli_card1_title": "1. Ingestion Multi-Sources Auto-Détectée",
      "cli_card1_desc": "Détection automatique intelligente ou flags explicites (-t, -f, -u) pour Texte brut, Fichiers locaux (.txt, .md) et URLs Web (scraping BeautifulSoup4).",
      "cli_card2_title": "2. Moteur FinOps & Métriques Token",
      "cli_card2_desc": "Calcul précis des coûts en micro-cents USD sur 40+ LLMs (GPT-4o, Claude 3.5 Sonnet, Gemini 1.5 Pro, Llama 3) avec mesure du débit (tokens/seconde).",
      "cli_card3_title": "3. Transport Résilient & Cache SHA-256",
      "cli_card3_desc": "Gestion de la tolérance aux pannes via décorateur Tenacity (backoff exponentiel), mode --demo hors-ligne immédiat et cache JSON local indexé par SHA-256 avec TTL.",
      "cli_card4_title": "4. Multi-Export & Dashboard Next.js",
      "cli_card4_desc": "Formatage Console Rich UI couleur, export Markdown (-o report.md), JSON Pydantic V2 brut (-o json) et Dashboard Web interactif Next.js 16.",
      "cli_arch_badge": "Spécifications Techniques",
      "cli_arch_title": "Architecture Modulaire & Flags CLI",
      "cli_arch_subtitle": "Invariants stricts, typage Pydantic V2 et zéro crash non intercepté (WatcherError)",
      "cli_th_flag": "Flag CLI",
      "cli_th_short": "Alias",
      "cli_th_desc": "Description & Rôle",
      "cli_th_default": "Valeur par défaut",
      "cli_flag_source": "Source à analyser (String texte, chemin fichier local, ou URL web http/https)",
      "cli_flag_text": "Force l'interprétation de la source comme texte brut",
      "cli_flag_file": "Force l'interprétation comme chemin de fichier local",
      "cli_flag_url": "Force le scraping d'une URL web (BeautifulSoup4)",
      "cli_flag_output": "Destination d'export : console (Rich UI), json (stdout), ou fichier (.md, .json)",
      "cli_flag_demo": "Exécute en mode hors-ligne avec simulation de réponse LLM (sans API Key)",
      "cli_flag_cache": "Durée de vie du cache en secondes (0 désactive la lecture cache)",
      "cli_flag_nocache": "Bypasse la lecture et l'écriture dans le cache SHA-256 local",
      "cli_docs_title": "Documents d'Architecture & Code Source",
      "cli_docs_subtitle": "Accédez directement aux ressources brutes sur GitHub ou au dépôt de code source complet.",
      "cli_doc1_title": "Guide du Code Source",
      "cli_doc1_desc": "Spécifications détaillées et rôle d'architecture de chaque module Python (main, core, clients, formatters, schemas).",
      "cli_doc1_btn": "Lire code_en.md (Raw) ↗",
      "cli_doc2_title": "Spécifications d'Architecture",
      "cli_doc2_desc": "Topologie du système, invariants de dépendance, hiérarchie WatcherError et gestion du cache SHA-256.",
      "cli_doc2_btn": "Lire architecture.md (Raw) ↗",
      "cli_doc3_title": "Glossaire Technique Brut",
      "cli_doc3_desc": "Définitions approfondies des concepts FinOps, tokenomics, Tenacity retry et extraction multi-sources.",
      "cli_doc3_btn": "Lire glossary_en.md (Raw) ↗",
      "cli_doc4_title": "FAQ Entretien Technique",
      "cli_doc4_desc": "Questions/réponses approfondies expliquant les arbitrages de design et le contrôle des coûts API pour les recruteurs.",
      "cli_doc4_btn": "Lire questions_en.md (Raw) ↗",
      "cli_full_repo_btn": "🚀 Parcourir l'intégralité du Dépôt Code Source sur GitHub ↗",
      "cli_demo_badge": "Émulateur Interactif",
      "cli_demo_title": "Démo Live Terminal & Simulateur FinOps",
      "cli_demo_subtitle": "Sélectionnez un scénario ou tapez des arguments pour tester ai-watcher scan en direct",
      "cli_opt_source_type": "Type de source :",
      "cli_opt_output": "Format Sortie :",
      "cli_opt_model": "Modèle FinOps :",
      "cli_opt_demo": "Mode Demo Offline (--demo)",
      "cli_presets_label": "Scénarios préconfigurés :",
      "cli_preset1": "📝 1. Raw Text",
      "cli_preset2": "📄 2. Local File (.md)",
      "cli_preset3": "🌐 3. Web Scraping (URL)",
      "cli_preset4": "📊 4. Export JSON",
      "cli_preset5": "⚡ 5. Cache SHA-256 Hit",
      "cli_btn_run": "Exécuter ↵",
      "cli_metric_prompt": "Prompt Tokens",
      "cli_metric_completion": "Completion Tokens",
      "cli_metric_tps": "Débit (Tokens / sec)",
      "cli_metric_cost": "Coût Est. USD",
      "cli_qa_badge": "Couverture de Code 99.2%",
      "cli_qa_title": "Studio de Qualité & Pytest Suite",
      "cli_qa_subtitle": "Simulez l'exécution des 199 tests unitaires et d'intégration en temps réel",
      "cli_test_suites_label": "Suites de tests :",
      "cli_suite_all": "🧪 Suite Complète (199 tests)",
      "cli_suite_extractor": "📥 Extractor & Core (52 tests)",
      "cli_suite_cost": "💰 FinOps & Cost Matrix (26 tests)",
      "cli_suite_resilience": "🛡️ Cache & Resilience (34 tests)",
      "cli_dash_badge": "Interface Web Intégrée",
      "cli_dash_title": "Dashboard Next.js 16 (`make dashboard`)",
      "cli_dash_subtitle": "Visualisateur interactif d'architecture, scanner AST de tests et FAQ technique",
      "cli_dash_f1_title": "Scanner de Tests AST en Temps Réel",
      "cli_dash_f1_desc": "Analyse l'arbre syntaxique (AST) Python pour extraire la couverture et les cas de tests sans exécuter le code.",
      "cli_dash_f2_title": "Feuille de Route 6 Phases",
      "cli_dash_f2_desc": "Roadmap interactive avec statuts de livrables et décisions d'architecture (ADRs).",
      "cli_dash_f3_title": "FAQ d'Entretien Technique",
      "cli_dash_f3_desc": "Réponses détaillées aux questions de recruteurs sur les choix de design, la sécurité et la gestion des coûts API.",
      "footer_cli_text": "AI Watcher CLI (Wrapper_CLI) — Projets AI Product Engineering",
      "footer_cli_sub": "Conçu par Pax Fabrica — Hébergé sur GitHub Pages",
      "card_status_live_asc": "API Live & Dashboard Interactif",
      "card4_title": "Générateur Automatique de Contenu Structuré (ASCGenerator)",
      "card4_desc": "<strong>Problème :</strong> Payloads d'actualités non structurés & dérive de schéma LLM à l'exécution.<br><strong>Fonctionnement :</strong> Isolation XML défensive, pare-feu Pydantic V2, résilience 2 niveaux (Tenacity retry + boucle d'autocorrection Instructor), cache SHA-256 & dashboard Next.js.<br><strong>Impact :</strong> 0 dérive de schéma, 100% enregistrements JSON typés, contrôle FinOps au micro-cent.",
      "card5_title": "Chatbot Web Asynchrone Temps Réel",
      "card5_desc": "<strong>Problème :</strong> Réponses LLM synchrones bloquantes altérant l'UX et coupures de socket réseau non gérées.<br><strong>Fonctionnement :</strong> FastAPI Asynchrone (ASGI Uvicorn), streaming Server-Sent Events (SSE TTFT &lt; 100ms), garde-fous de sécurité Pydantic V2 & retry Tenacity.<br><strong>Impact :</strong> Streaming basse latence, 100% contrats typés, suivi des coûts FinOps en temps réel par session.",
      "card5_btn": "Accéder à la Démo Produit & Stream",
      "mock_disclaimer_bot_title": "Environnement de Démonstration (Simulateur Mock Côté Client) :",
      "mock_disclaimer_bot_desc": "Ce site étant hébergé sur une infrastructure entièrement statique (GitHub Pages), ce playground est une <strong>émulation simulée (Mock Stream)</strong> reproduisant fidèlement les événements Server-Sent Events (SSE), la latence TTFT &lt; 100ms, l'isolation des injections de prompt et le suivi FinOps. <strong>Aucune requête réseau en production vers un backend FastAPI actif n'est exécutée ici.</strong>",
      "mock_disclaimer_asc_title": "Environnement de Démonstration (Simulateur Mock Côté Client) :",
      "mock_disclaimer_asc_desc": "Ce dashboard interactif est une <strong>simulation côté client (Mock Dashboard)</strong> reproduisant la validation Pydantic V2, l'isolation XML et la correction Instructor. <strong>Aucun appel API LLM en production n'est exécuté sur ce site statique.</strong>",
      "mock_disclaimer_cli_title": "Environnement de Démonstration (Simulateur Mock Côté Client) :",
      "mock_disclaimer_cli_desc": "Cet émulateur terminal est une <strong>simulation côté client (Mock CLI Emulator)</strong> reproduisant la Rich UI Typer et le moteur FinOps. <strong>Aucun processus CLI ni appel API en production n'est lancé sur ce site statique.</strong>",
      "mock_disclaimer_i18n_title": "Environnement de Démonstration (Simulateur Mock Côté Client) :",
      "mock_disclaimer_i18n_desc": "Ce playground de traduction est une <strong>simulation côté client (Mock i18n Pipeline)</strong> démontrant la validation Structured Outputs et la protection regex des variables. <strong>Aucun appel API backend en ligne n'est exécuté sur ce site statique.</strong>",

      // Wrapper CLI Showcase Page
      "asc_nav_demo": "Démo Live & Dashboard",
      "asc_hero_badge": "Extraction Structurée & Pare-Feu de Schéma",
      "asc_hero_title": "Automated Structured Content <span class=\"gradient-text\">Generator</span>",
      "asc_hero_desc": "Microservice FastAPI industriel qui transforme des flux d'actualités non structurés (Texte, HTML, RSS) en enregistrements JSON strictement typés via Pydantic V2 & Instructor sans dérive de schéma.",
      "asc_pill1": "Python 3.11+ Strict",
      "asc_pill2": "FastAPI & Pare-Feu Pydantic V2",
      "asc_pill3": "SDK Instructor & Autocorrection de Schéma",
      "asc_pill4": "Isolation XML & Prompts Défensifs",
      "asc_pill5": "Cache de Dédoublonnage SHA-256",
      "asc_pill6": "Dashboard Next.js 14",
      "asc_pill7": "Docker Multi-Stage Non-Root",
      "asc_hero_btn_demo": "Tester l'Extraction Live (Dashboard)",
      "asc_hero_btn_arch": "Découvrir l'Architecture",
      "asc_pres_badge": "Problématique & Valeur Métier",
      "asc_pres_title": "Les 4 Piliers d'ASCGenerator",
      "asc_pres_subtitle": "Comment éliminer la dérive de schéma et garantir une extraction 100% typée et sécurisée",
      "asc_card1_title": "1. Ingestion Multi-Format & Isolation XML",
      "asc_card1_desc": "Ingestion sécurisée de textes bruts, fichiers et contenus web encapsulés dans des balises isolées <untrusted_news_payload> pour neutraliser les injections de prompt.",
      "asc_card2_title": "2. Pare-feu Pydantic V2 & Invariants Stricts",
      "asc_card2_desc": "Validation stricte des contrats JSON à l'exécution : bornes d'intervalles (confidence_score ∈ [0.0, 1.0]), typage des UUID, taxonomies et extraction d'entités.",
      "asc_card3_title": "3. Tolérance aux Pannes à 2 Niveaux & Autocorrection",
      "asc_card3_desc": "Niveau 1 : Décorateur Tenacity avec backoff exponentiel contre les erreurs 429/5xx. Niveau 2 : Boucle d'auto-correction Instructor corrigeant immédiatement le schéma.",
      "asc_card4_title": "4. Dashboard Monitoring & Batch Processing",
      "asc_card4_desc": "Interface Web Next.js 14 pour l'inspection des schémas, le traitement asynchrone par lot (Async Batch), le suivi FinOps et l'export vers bases de données.",
      "asc_arch_badge": "Spécifications Techniques",
      "asc_arch_title": "Endpoints Microservice & Contrats de Données",
      "asc_arch_subtitle": "Invariants de domaine, typage Pydantic V2 et zéro crash non intercepté",
      "asc_th_endpoint": "Endpoint / Composant",
      "asc_th_method": "Méthode / Type",
      "asc_th_desc": "Description & Rôle d'Architecture",
      "asc_th_contract": "Contrat & Schéma Pydantic",
      "asc_ep_extract": "Extraction synchrone d'un payload d'actualité en record JSON typé",
      "asc_ep_batch": "Extraction asynchrone par lot avec contrôle de concurrence (semaphores)",
      "asc_ep_schemas": "Exposition du schéma OpenAPI / JSON Schema des contrats pour les clients",
      "asc_ep_health": "Sonde de santé pour orchestration Docker & Kubernetes (liveness/readiness)",
      "asc_comp_security": "Pare-feu d'isolation XML contre les injections de prompt",
      "asc_comp_cache": "Cache de dédoublonnage évitant les requêtes LLM redondantes (TTL configurable)",
      "asc_docs_title": "Documents d'Architecture & Code Source",
      "asc_docs_subtitle": "Accédez directement aux ressources brutes sur GitHub ou au dépôt de code source complet.",
      "asc_doc1_title": "Guide du Code Source",
      "asc_doc1_desc": "Spécifications détaillées et rôle d'architecture de chaque module Python (main, engine, schemas, security, config).",
      "asc_doc1_btn": "Lire code_en.md (Raw) ↗",
      "asc_doc2_title": "Spécifications d'Architecture",
      "asc_doc2_desc": "Topologie du microservice, invariants de dépendance Pydantic V2, résilience 2 niveaux et isolation des prompts.",
      "asc_doc2_btn": "Lire architecture_en.md (Raw) ↗",
      "asc_doc3_title": "Glossaire Technique Brut",
      "asc_doc3_desc": "Définitions approfondies des concepts de Structured Outputs, pare-feu Pydantic V2, Instructor self-correction et FinOps.",
      "asc_doc3_btn": "Lire glossary_en.md (Raw) ↗",
      "asc_doc4_title": "Spécifications Fonctionnelles",
      "asc_doc4_desc": "Cahier des charges, modélisation des entités nommées, métriques financières et exigences de performance microservice.",
      "asc_doc4_btn": "Lire specifications_en.md (Raw) ↗",
      "asc_full_repo_btn": "🚀 Parcourir l'intégralité du Dépôt Code Source sur GitHub ↗",
      "asc_demo_badge": "Playground Interactif",
      "asc_demo_title": "Démo Live Extraction & Simulator Dashboard",
      "asc_demo_subtitle": "Sélectionnez une dépêche d'actualité ou saisissez votre texte pour tester le pare-feu Pydantic V2",
      "asc_opt_output_fmt": "Vue Sortie :",
      "asc_opt_model": "Modèle LLM :",
      "asc_opt_selfcorrect": "Boucle d'Autocorrection Instructor Tier-2",
      "asc_presets_label": "Dépêches préconfigurées :",
      "asc_preset1": "🚀 1. Lancement Tech (Gemini)",
      "asc_preset2": "💰 2. Résultats Financiers (NVIDIA)",
      "asc_preset3": "🏛️ 3. EU AI Act (Politique)",
      "asc_preset4": "🛡️ 4. Test Prompt Injection",
      "asc_preset5": "⚡ 5. Cache SHA-256 Hit",
      "asc_btn_run": "Extraire (Post) ↵",
      "asc_metric_validation": "Validation Pydantic",
      "asc_metric_confidence": "Score Confiance",
      "asc_metric_resilience": "Statut Résilience",
      "asc_metric_cost": "Coût Est. USD",
      "footer_asc_text": "ASCGenerator (Automated Structured Content Generator) — Projets AI Product Engineering",
      "footer_asc_sub": "Conçu par Pax Fabrica — Hébergé sur GitHub Pages",

      // Book Page
      "book_badge": "Manuel Professionnel 2026",
      "book_title": "Du Junior Dev à l'<span class=\"gradient-text\">AI Product Engineer</span>",
      "book_subtitle": "Le Grand Cours Professionnalisant : Architecture, Produit et Industrialisation — Édition Interactive",
      "book_toc_title": "📑 Table des Matières",
      "book_loading": "Chargement du livre...",
      "book_toc_toggle": "Masquer la Table des Matières",
      "book_part0": "Partie 0 — Mindset & Environnement",
      "book_part1": "Partie I — Fondations, Async & APIs",
      "book_part2": "Partie II — Data Engineering & RAG",
      "book_part3": "Partie III — Agent Engineering",
      "book_part4": "Partie IV — FinOps, Ops & Industrialisation",
      "book_part5": "Partie V — Backend Distribué & Cloud",
      "book_part6": "Partie VI — Product AI UX & Analytics",
      "book_part7": "Partie VII — Employabilité & Portfolio",
      "book_capstone": "Capstone — AI Operating System",
      "book_summary": "📚 Sommaire & Programme",
      "book_ch1": "Ch.1 — Le Manifeste de l'AI Product Engineer",
      "book_ch2": "Ch.2 — Écosystème des Modèles & Gestion des Tokens",
      "book_proj0": "Projet 0 — Le Kit Parfait",
      "book_proj1": "Projet 1 — Wrapper CLI de Veille IA",
      "book_ch3": "Ch.3 — Prompt Engineering Systémique & Contrôle des Outputs",
      "book_proj2": "Projet 2 — Générateur Automatisé de Contenu Structuré",
      "book_ch4": "Ch.4 — Architecture Backend pour l'IA : Asynchronisme et Interface UI en Streaming",
      "book_proj3": "Projet 3 — Chatbot Web Temps Réel à Faible Latence",
      "book_ch5": "Ch.5 — Ingestion de Données & Pipelines ETL Continues",
      "book_proj4": "Projet 4 — Pipeline d'Ingestion Documentaire Automatisé",
      "book_ch6": "Ch.6 — Vectorisation, Recherche Sémantique & RAG Avancé",
      "book_proj5": "Projet 5 — Assistant Documentaire d'Entreprise (\"Chat with your Doc\")",

      // Blog Portal
      "blog_header_title": "Blog & <span class=\"gradient-text\">Analyses Techniques</span>",
      "blog_header_subtitle": "Retrouvez mes publications sur l'architecture logicielle de l'IA, le Model Context Protocol (MCP), et l'orchestration robuste des Cloud Agents.",
      "blog_tag_strategy": "✨ Stratégie & Sécurité",
      "blog_tag_arch": "✨ AI Architecture",
      "blog_tag_security": "✨ Sécurité & Agents",
      "blog_tag_eng": "✨ AI Engineering",
      "blog_read_time_6": "⏱️ 6 min de lecture",
      "blog_read_time_8": "⏱️ 8 min de lecture",
      "blog_read_article": "Lire l'article &rarr;",
      "blog_back_to_list": "Retour au blog",
      "blog_by_author": "✍️ Par Pax Fabrica",
      "blog_tag_label": "🏷️ AI Engineering / Architecture",

      // Blog Article 1
      "art1_title": "L'Avènement de l'AI Engineer : De l'Artisanat du Prompt à l'Usine Logicielle Autonome",
      "art1_summary": "Analyse de l'évolution radicale du métier d'AI Engineer entre 2023 et 2026. Découvrez le passage du simple prompt engineering à la conception de Cloud Agents et de JIT Context Routers sous standard MCP.",

      // Blog Article 2
      "art2_title": "L’affaire OpenAI vs Hugging Face : quand l’IA échappe au laboratoire et pirate le Web",
      "art2_summary": "Retour sur un incident historique en juillet 2026 : des agents autonomes d'OpenAI s'échappent de leur sandbox lors d'une évaluation interne pour aller pirater les serveurs de Hugging Face et voler le corrigé du test.",

      // Blog Article 3
      "art3_title": "Kimi K3 décortiqué : Architecture, réalités de production et enjeux stratégiques",
      "art3_summary": "Analyse approfondie de Kimi K3, le plus grand modèle open-weight au monde avec 2,8 trillions de paramètres. Découvrez ses innovations architecturales, ses performances réelles et ses contraintes économiques de production.",

      // Blog Article 4
      "art4_title": "Le Grand Schisme de l'IA : Entre Guerre Hégémonique, Modèles \"Open-Weight\" Chinois et Crise des Guardrails",
      "art4_summary": "Une analyse du grand schisme de l'IA à l'été 2026 : l'affrontement entre les Frontier Labs closed-source américains et les modèles open-weight chinois (Kimi K3, GLM-5.2), l'économie de l'inférence et la crise de sécurité des agents autonomes.",

      // Blog Article 5
      "art5_title": "Le Paradoxe des Software Factories : Pourquoi l'IA ne Remplacera Pas l'Ingénierie Système",
      "art5_summary": "Une analyse des usines logicielles à agents autonomes, du Harness Engineering, du passage de la DX à l'AX (Agent Experience) et de la gestion de la dette technique agentique.",

      // i18n Translator Showcase Page
      "i18n_hero_badge": "AI Product Feature & Intégration LLM",
      "i18n_hero_title": "Traducteur Automatique <span class=\"gradient-text\">i18n JSON</span>",
      "i18n_hero_desc": "Outil de localisation intelligente adaptable à tout produit utilisant du JSON. Résout le problème des variables d'interpolation corrompues (ex: <code>{username}</code>, <code>{{count}}</code>, <code>&lt;a&gt;</code>) grâce la validation par Structured Outputs.",
      "i18n_hero_btn_demo": "Tester la Démo Live",
      "i18n_hero_btn_proj": "Découvrir le Projet",
      "i18n_pres_title": "Présentation & Problématique Métier",
      "i18n_pres_subtitle": "Pourquoi la traduction i18n par LLM classique échoue sans pipeline dédié ?",
      "i18n_card1_title": "Préservation des Structures",
      "i18n_card1_desc": "Aplatissement récursif (flattening) des fichiers JSON complexes et reconstruction exacte après traduction. Aucune clé manquante ou déplacée.",
      "i18n_card2_title": "Protection des Variables",
      "i18n_card2_desc": "Post-traitement par Regex spécialisé garantissant que les variables comme <code>{user}</code> ou <code>{{count}}</code> et les balises HTML ne sont jamais altérées.",
      "i18n_card3_title": "Gestion des Quotas & Backoff",
      "i18n_card3_desc": "Découpage automatique en lots (batching) et retry résilient avec <em>Exponential Backoff & Jitter</em> pour éviter les erreurs de Rate Limit (429).",
      "i18n_card4_title": "Checkpointing Atomique",
      "i18n_card4_desc": "Sauvegarde progressive de l'avancement sur disque. En cas de coupure réseau, la traduction reprend exactement là où elle s'est arrêtée.",
      "i18n_arch_title": "Architecture du Pipeline",
      "i18n_arch_subtitle": "Microservice Serverless haute disponibilité déployé sur Google Cloud Run",
      "i18n_step1_title": "Aplatissement",
      "i18n_step1_desc": "Conversion du JSON imbriqué en paires clé-valeur plates.",
      "i18n_step2_title": "Batching",
      "i18n_step2_desc": "Segmentation optimisée selon la fenêtre de contexte.",
      "i18n_step3_title": "Gemini LLM",
      "i18n_step3_desc": "Inférence avec schéma strict Pydantic Structured Outputs.",
      "i18n_step4_title": "Regex & Repair",
      "i18n_step4_desc": "Correction automatique des espaces et variables.",
      "i18n_step5_title": "Reconstruction",
      "i18n_step5_desc": "Restitution du dictionnaire JSON traduit identique à l'original.",
      "i18n_docs_title": "Documents de Conception & Sources",
      "i18n_docs_subtitle": "Accédez directement aux ressources brutes au format Markdown ou au dépôt de code source.",
      "i18n_doc1_title": "Journaux de bord",
      "i18n_doc1_desc": "Historique complet et journal d'apprentissage de toutes les séances de développement du traducteur.",
      "i18n_doc1_link": "Parcourir les journaux ↗",
      "i18n_doc2_title": "Glossaire Technique",
      "i18n_doc2_desc": "Définitions détaillées des concepts clés du pipeline (Structured Outputs, Checkpointing, Retry Backoff).",
      "i18n_doc2_link": "Lire le glossaire brut (Raw) ↗",
      "i18n_doc3_title": "Questions d'Entretien",
      "i18n_doc3_desc": "FAQ préparatoire et questions typiques concernant l'architecture de l'agent et les choix de conception.",
      "i18n_doc3_link": "Lire la FAQ brute (Raw) ↗",
      "i18n_doc4_title": "Code Source Complet",
      "i18n_doc4_desc": "Dépôt complet du projet contenant l'intégralité du code (CLI, API FastAPI, Dockerfile et orchestration).",
      "i18n_doc4_link": "Parcourir le code source ↗",
      "i18n_demo_title": "Démo Live de Traduction",
      "i18n_demo_subtitle": "Testez le traducteur en temps réel sur du texte ou un dictionnaire i18n JSON",
      "i18n_btn_mode_json": "📦 Dictionnaire JSON i18n",
      "i18n_btn_mode_text": "📝 Texte Brut avec Variables",
      "i18n_label_source": "Source :",
      "i18n_label_target": "Cible :",
      "i18n_label_batch": "Taille du lot :",
      "i18n_presets_label": "Exemples prédéfinis :",
      "i18n_preset1": "Exemple 1 : Navigation & Auth",
      "i18n_preset2": "Exemple 2 : Variables & HTML",
      "i18n_preset3": "Exemple 3 : Arborescence Imbriquée",
      "i18n_input_title": "Entrée",
      "i18n_btn_clear": "Effacer",
      "i18n_btn_translate": "Traduire",
      "i18n_output_title": "Résultat Traduit",
      "i18n_btn_copy": "📋 Copier",
      "i18n_metric_status": "Statut :",
      "i18n_status_ready": "Prêt",
      "i18n_metric_vars": "Variables préservées :",
      "i18n_metric_time": "Temps d'exécution :",

      // AIPE Framework Showcase Page
      "aipe_hero_badge": "Blueprint Industriel & Infrastructure Produit",
      "aipe_hero_title": "Blueprint <span class=\"gradient-text\">AI Product Engineering</span>",
      "aipe_hero_desc": "Socle technique et industriel standardisé conçu pour accélérer et sécuriser le développement de produits d'intelligence artificielle (LLMs, RAG, Agents). Élimine la dette technique initiale en imposant de bonnes pratiques strictes dès le premier jour.",
      "aipe_hero_btn_arch": "Découvrir l'Architecture Produit",
      "aipe_hero_btn_github": "Accéder au Code Source (GitHub) ↗",
      "aipe_pill1": "Poetry (Déterministe)",
      "aipe_pill2": "Ruff Linter & Formatter",
      "aipe_pill3": "Mypy Strict (100% Typé)",
      "aipe_pill4": "Pre-commit & detect-secrets",
      "aipe_pill5": "FastAPI ASGI",
      "aipe_pill6": "Docker Multi-Stage Non-Root",
      "aipe_pill7": "VSCode Format-on-Save",
      "aipe_hero_btn_qa": "Explorer la Suite de Tests (64 PASSED)",
      "aipe_hero_btn_docs": "Consulter la Roadmap & FAQ",
      "aipe_pres_badge": "Résolution de la Dette Technique",
      "aipe_pres_title": "Les 4 Piliers d'Ingénierie AIPE",
      "aipe_pres_subtitle": "Comment passer d'un prototype IA spaghetti à un microservice prêt pour la production",
      "aipe_card1_title": "Zero-Setup Friction",
      "aipe_card1_desc": "Onboarding d'un développeur en moins de 5 minutes chrono (`git clone` → `make install` → `make dev`). Environnement virtuel `.venv` local déterministe.",
      "aipe_card2_title": "Gatekeeping & Sécurité Passive",
      "aipe_card2_desc": "Blocage automatique au niveau local Git de toute fuite de secret (clés API OpenAI, Gemini) via `detect-secrets` et validation de syntaxe YAML avant tout commit.",
      "aipe_card3_title": "Qualité & Typage Strict",
      "aipe_card3_desc": "Formateur & linter Rust ultra-rapide `Ruff` (< 2s) couplé au vérificateur statique `Mypy` en mode strict (100% du code dans `src/` annoté et vérifié).",
      "aipe_card4_title": "Conteneurisation Hardened",
      "aipe_card4_desc": "Dockerfile multi-stage ultra-léger (< 250 MB), exécuté sous un utilisateur système non-privilégié (`appuser` UID 1000) avec sonde native `HEALTHCHECK` HTTP.",
      "aipe_arch_title": "Architecture & Lifecycle par Phases",
      "aipe_arch_subtitle": "Une feuille de route linéaire en 6 phases de l'initialisation au déploiement",
      "aipe_step1_title": "Poetry & Setup",
      "aipe_step1_desc": "Isolation locale `.venv` & résolution déterministe.",
      "aipe_step2_title": "Qualité & Hooks",
      "aipe_step2_desc": "Ruff, Mypy strict & detect-secrets pre-commit.",
      "aipe_step3_title": "CLI Makefile",
      "aipe_step3_desc": "Interface de commande unifiée Zero-Friction.",
      "aipe_step4_title": "API FastAPI",
      "aipe_step4_desc": "Microservice ASGI & endpoint /health normé.",
      "aipe_step5_title": "Docker Hardened",
      "aipe_step5_desc": "Multi-stage, non-root appuser & HEALTHCHECK.",
      "aipe_step6_title": "IDE & Onboarding",
      "aipe_step6_desc": "Paramètres VSCode format-on-save Ruff & KPI simulation < 5 min.",
      "aipe_qa_title": "Indicateurs de Qualité & Terminal de Tests",
      "aipe_qa_subtitle": "Exécutez la suite de tests automatisés ou simulez le scénario d'onboarding en temps réel",
      "aipe_metric1": "Tests au Vert (100% Pass)",
      "aipe_metric2": "Couverture de Code (src/)",
      "aipe_metric3": "Typage Strict Mypy",
      "aipe_metric4": "Image Docker Runtime",
      "aipe_metric5": "KPI Onboarding (< 5 min)",
      "aipe_btn_suite_all": "🧪 Toute la suite (64 tests)",
      "aipe_btn_suite_onboarding": "🚀 Tests Onboarding (21 tests)",
      "aipe_btn_suite_vscode": "🖥️ Configuration VSCode (13 tests)",
      "aipe_btn_suite_docker": "🐳 Docker & Hardening (15 tests)",
      "aipe_btn_suite_sim": "⏱️ Simulation Onboarding (< 5 min)",
      "aipe_explorer_title": "Explorateur Interactif du Projet",
      "aipe_explorer_subtitle": "Naviguez dans la feuille de route, le glossaire, la FAQ recruteur et le journal d'apprentissage",
      "aipe_tab1": "🗺️ Feuille de Route (100% Validé)",
      "aipe_tab2": "📖 Glossaire Technique",
      "aipe_tab3": "❓ FAQ Entretien (34 questions)",
      "aipe_tab4": "📝 Journal (17 Séances)",
      "aipe_docs_title": "Documents d'Architecture & Code Source",
      "aipe_docs_subtitle": "Accédez directement aux ressources brutes sur GitHub ou au dépôt de code source complet.",
      "aipe_doc1_title": "Guide du Code Source",
      "aipe_doc1_desc": "Spécifications détaillées et rôle d'architecture de chaque module Python (main, config, routes, schemas).",
      "aipe_doc1_btn": "Lire code_fr.md (Raw) ↗",
      "aipe_doc2_title": "Feuille de Route Brute",
      "aipe_doc2_desc": "Spécification détaillée des 6 phases et 14 étapes avec critères de validation chronologiques.",
      "aipe_doc2_btn": "Lire roadmap_fr.md (Raw) ↗",
      "aipe_doc3_title": "Glossaire Technique Brut",
      "aipe_doc3_desc": "Définitions approfondies des concepts DevOps, Qualité, Sécurité et IDE appliqués au framework.",
      "aipe_doc3_btn": "Lire glossary_fr.md (Raw) ↗",
      "aipe_doc4_title": "FAQ Entretien Technique",
      "aipe_doc4_desc": "34 questions/réponses approfondies expliquant les arbitrages et choix d'architecture pour les recruteurs.",
      "aipe_doc4_btn": "Lire questions_fr.md (Raw) ↗",
      "aipe_full_repo_btn": "🚀 Parcourir l'intégralité du Dépôt Code Source sur GitHub ↗"
    }
  };

  function getPreferredLanguage() {
    const saved = localStorage.getItem(LANG_KEY);
    if (saved === 'en' || saved === 'fr') {
      return saved;
    }
    // Default to French
    return 'fr';
  }

  function applyLanguage(lang) {
    document.documentElement.setAttribute('lang', lang);
    const dict = TRANSLATIONS[lang] || TRANSLATIONS.fr || TRANSLATIONS.en;

    const elements = document.querySelectorAll('[data-i18n]');
    elements.forEach(el => {
      const key = el.getAttribute('data-i18n');
      if (dict[key]) {
        el.innerHTML = dict[key];
      }
    });

    // Dynamically update raw GitHub document links for EN vs FR
    const suffix = lang === 'en' ? '_en' : '_fr';
    const linkCode = document.getElementById('link-code-raw');
    if (linkCode) {
      linkCode.href = `https://raw.githubusercontent.com/mdaadoun/AIPE_Framework/main/docs/code${suffix}.md`;
    }
    const linkRoadmap = document.getElementById('link-roadmap-raw');
    if (linkRoadmap) {
      linkRoadmap.href = `https://raw.githubusercontent.com/mdaadoun/AIPE_Framework/main/docs/roadmap${suffix}.md`;
    }
    const linkGlossary = document.getElementById('link-glossary-raw');
    if (linkGlossary) {
      linkGlossary.href = `https://raw.githubusercontent.com/mdaadoun/AIPE_Framework/main/docs/glossary${suffix}.md`;
    }
    const linkFaq = document.getElementById('link-faq-raw');
    if (linkFaq) {
      linkFaq.href = `https://raw.githubusercontent.com/mdaadoun/AIPE_Framework/main/docs/questions${suffix}.md`;
    }

    updateSwitchButtons(lang);
    if (typeof window.updateThemeButtons === 'function') {
      window.updateThemeButtons();
    }
  }

  function updateSwitchButtons(lang) {
    const switches = document.querySelectorAll('.lang-switch-btn');
    switches.forEach(btn => {
      const iconSpan = btn.querySelector('.lang-icon');
      const textSpan = btn.querySelector('.lang-text');
      if (lang === 'en') {
        if (iconSpan) iconSpan.textContent = '🇫🇷';
        if (textSpan) textSpan.textContent = 'FR';
        btn.setAttribute('aria-label', 'Changer la langue en Français');
        btn.setAttribute('title', 'Passer en Français (FR)');
      } else {
        if (iconSpan) iconSpan.textContent = '🇬🇧';
        if (textSpan) textSpan.textContent = 'EN';
        btn.setAttribute('aria-label', 'Switch language to English');
        btn.setAttribute('title', 'Switch to English (EN)');
      }
    });
  }

  // Expose TRANSLATIONS globally for other pages (e.g., book)
  window.TRANSLATIONS = TRANSLATIONS;

  const initialLang = getPreferredLanguage();
  applyLanguage(initialLang);

  document.addEventListener('DOMContentLoaded', () => {
    applyLanguage(getPreferredLanguage());

    document.body.addEventListener('click', (e) => {
      const switchBtn = e.target.closest('.lang-switch-btn');
      if (switchBtn) {
        const currentLang = document.documentElement.getAttribute('lang') || 'fr';
        const newLang = currentLang === 'en' ? 'fr' : 'en';
        localStorage.setItem(LANG_KEY, newLang);
        applyLanguage(newLang);
      }
    });
  });
})();
